"""
Report Notification Service
Handles sending emails when an admin generates and prints a Warehouse AI Report.
"""

from typing import List
from datetime import datetime
from sqlalchemy.orm import Session
from app.services.notification_service import NotificationService, EmailConfig
from app.models import Profile, Department

class ReportEmailTemplates:
    @staticmethod
    def report_printed_notification(admin_name: str, warehouse_name: str = "Colombo Facility", generated_at: str = None) -> tuple:
        """Email template for AI Warehouse Report generation"""
        if not generated_at:
            generated_at = datetime.now().strftime('%B %d, %Y at %I:%M %p')
            
        subject = f"PredictiX Alert: Warehouse AI Report Generated - {warehouse_name}"
        
        html_body = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6; margin: 0; padding: 0; background-color: #f9f9f9; }}
                    .container {{ max-width: 650px; margin: 30px auto; background-color: #ffffff; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }}
                    .header {{ background: linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%); color: white; padding: 25px 30px; }}
                    .header h2 {{ margin: 0; font-size: 24px; font-weight: 600; letter-spacing: 0.5px; }}
                    .header .subtitle {{ font-size: 14px; opacity: 0.9; margin-top: 5px; }}
                    .content {{ padding: 30px; }}
                    .greeting {{ font-size: 16px; font-weight: 500; margin-bottom: 20px; }}
                    .info-box {{ background: #f8fafc; padding: 20px; border-left: 4px solid #0ea5e9; margin: 20px 0; border-radius: 0 4px 4px 0; }}
                    .info-row {{ display: flex; margin-bottom: 10px; font-size: 14px; }}
                    .info-label {{ font-weight: 600; width: 140px; color: #475569; }}
                    .info-value {{ color: #0f172a; font-weight: 500; }}
                    .message {{ margin-bottom: 20px; font-size: 15px; color: #475569; }}
                    .footer {{ background: #f1f5f9; padding: 20px 30px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h2>Warehouse AI Report Generated</h2>
                        <div class="subtitle">PredictiX Advanced Analytics</div>
                    </div>
                    <div class="content">
                        <div class="greeting">Hello Team,</div>
                        <p class="message">This is an automated notification that a new comprehensive AI Warehouse Report has been successfully generated and exported from the PredictiX Dashboard.</p>
                        
                        <div class="info-box">
                            <div class="info-row">
                                <div class="info-label">Generated By:</div>
                                <div class="info-value">{admin_name}</div>
                            </div>
                            <div class="info-row">
                                <div class="info-label">Facility:</div>
                                <div class="info-value">{warehouse_name}</div>
                            </div>
                            <div class="info-row">
                                <div class="info-label">Timestamp:</div>
                                <div class="info-value" style="color: #0ea5e9;">{generated_at}</div>
                            </div>
                            <div class="info-row">
                                <div class="info-label">Status:</div>
                                <div class="info-value"><span style="background-color: #d1fae5; color: #065f46; padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: 600;">SUCCESS</span></div>
                            </div>
                        </div>
                        
                        <p class="message">The report contains up-to-date AI diagnostics on fleet health, SHAP failure predictions, maintenance logs, and prescriptive KB recommendations. Please coordinate with the generating admin if you require a copy of the exported PDF.</p>
                        
                        <p style="font-size: 14px; color: #64748b; margin-top: 30px;">Best regards,<br><b>PredictiX System Architecture</b></p>
                    </div>
                    <div class="footer">
                        <p style="margin: 0;">This is an automated security and compliance notification. Please do not reply directly to this email.</p>
                    </div>
                </div>
            </body>
        </html>
        """
        return subject, html_body

class ReportNotificationService:
    @staticmethod
    def notify_on_report_print(db: Session, admin_id: str) -> bool:
        """
        Sends an email notifying that the report has been printed.
        As requested, hardcodes the target email to sharadaabeywickrama@gmail.com,
        and optionally sends to the admin.
        """
        try:
            # Get admin details
            admin = db.query(Profile).filter(Profile.id == admin_id).first()
            admin_name = admin.full_name if admin else "System Administrator"
            admin_email = admin.email if admin else None
            
            # The requested target email
            target_department_email = "sharadaabeywickrama@gmail.com"
            
            # Build recipient list ensuring uniqueness
            recipients = {target_department_email}
            if admin_email:
                recipients.add(admin_email)
                
            email_list = list(recipients)
            print(f"[NOTIFICATION] Sending Report Print email to: {email_list}")
            
            subject, html_body = ReportEmailTemplates.report_printed_notification(
                admin_name=admin_name
            )
            
            # Use existing NotificationService sender logic
            result = NotificationService.send_email(email_list, subject, html_body)
            return result
            
        except Exception as e:
            print(f"[NOTIFICATION-ERROR] Failed to send report notification: {str(e)}")
            return False
