-- ============================================================================
-- PredictiX Knowledge Base Setup SQL for Supabase
-- ============================================================================
-- Run these SQL commands in your Supabase SQL editor
-- Make sure pgvector extension is enabled first

-- ============================================================================
-- 1. Enable pgvector Extension (if not already enabled)
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- 2. Create knowledge_base table
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.knowledge_base (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL,
    source TEXT,
    embedding vector(384),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 3. Create indexes for better performance
-- ============================================================================
-- Index on category for filtering
CREATE INDEX IF NOT EXISTS knowledge_base_category_idx ON public.knowledge_base(category);

-- Index on created_at for sorting
CREATE INDEX IF NOT EXISTS knowledge_base_created_at_idx ON public.knowledge_base(created_at DESC);

-- Vector index for semantic search (HNSW for best performance)
CREATE INDEX IF NOT EXISTS knowledge_base_embedding_idx 
    ON public.knowledge_base 
    USING hnsw (embedding vector_cosine_ops);

-- ============================================================================
-- 4. Create match_knowledge RPC function for semantic search
-- ============================================================================
CREATE OR REPLACE FUNCTION public.match_knowledge(
    query_embedding vector(384),
    match_count int DEFAULT 5,
    similarity_threshold float DEFAULT 0.3
)
RETURNS TABLE(
    id UUID,
    title TEXT,
    content TEXT,
    category TEXT,
    source TEXT,
    similarity FLOAT,
    created_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        kb.id,
        kb.title,
        kb.content,
        kb.category,
        kb.source,
        (1 - (kb.embedding <=> query_embedding))::float as similarity,
        kb.created_at
    FROM public.knowledge_base kb
    WHERE kb.embedding IS NOT NULL
        AND (1 - (kb.embedding <=> query_embedding)) > similarity_threshold
    ORDER BY kb.embedding <=> query_embedding
    LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 5. Create trigger to update updated_at timestamp
-- ============================================================================
CREATE OR REPLACE FUNCTION public.update_knowledge_base_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS knowledge_base_updated_at_trigger ON public.knowledge_base;

CREATE TRIGGER knowledge_base_updated_at_trigger
    BEFORE UPDATE ON public.knowledge_base
    FOR EACH ROW
    EXECUTE FUNCTION public.update_knowledge_base_updated_at();

-- ============================================================================
-- 6. Insert sample knowledge base entries
-- ============================================================================
-- Note: Embeddings will be generated by generate_embeddings.py
-- These are just sample entries for testing

INSERT INTO public.knowledge_base (title, content, category, source)
VALUES
    (
        'Basic Maintenance Schedule',
        'Regular maintenance includes: oil changes every 5,000 km, tire rotation every 10,000 km, brake inspection every 20,000 km, and coolant check every 30,000 km.',
        'maintenance',
        'service_manual_v1'
    ),
    (
        'Tire Maintenance Guide',
        'Check tire pressure monthly (find correct PSI on driver''s door jamb). Inspect tread depth using penny test. Replace tires when tread depth reaches 4/32 inch. Rotate tires every 10,000 km for even wear.',
        'maintenance',
        'tire_guide_2025'
    ),
    (
        'Brake System Troubleshooting',
        'Common brake issues: soft pedal (low fluid or air in lines), grinding noise (worn pads), pulling to one side (uneven pad wear). Always check fluid level first before diagnosing further problems.',
        'troubleshooting',
        'brake_manual'
    )
ON CONFLICT DO NOTHING;

-- ============================================================================
-- 7. Verify setup
-- ============================================================================
-- Run this to check if everything is set up correctly:
-- SELECT COUNT(*) as total_entries FROM public.knowledge_base;
-- SELECT * FROM public.knowledge_base LIMIT 3;

-- ============================================================================
-- SETUP COMPLETE
-- ============================================================================
-- Next steps:
-- 1. Run app/knowledge/generate_embeddings.py to generate embeddings
-- 2. Use /chatbot/kb/add endpoint to add more entries
-- 3. Use /chatbot/ask endpoint to query the chatbot

-- For troubleshooting:
-- - Check if pgvector extension is enabled: SELECT extname FROM pg_extension WHERE extname = 'vector';
-- - Check function exists: SELECT * FROM pg_proc WHERE proname = 'match_knowledge';
-- - Check embeddings are generated: SELECT COUNT(*) FROM public.knowledge_base WHERE embedding IS NOT NULL;
