"""PredictiX Chatbot – Pure-Python Tool Handlers & Zero-Token Handlers.

Architecture:
  - Zero-Token handlers: Greeting, Navigation, WhoAmI, FAQ
    → No LLM call at all. Instant, deterministic responses.
  - Database handler: executes SQL generated by a sub-agent
  - Knowledge handler: semantic search on the knowledge base
  - Prediction handler: queries all ML prediction tables
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Optional

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.db.supabase_client import supabase

log = logging.getLogger("predictix.tools")


# ─── Context ─────────────────────────────────────────────────────────────────

@dataclass
class ToolContext:
    """Per-request context handed to every handler."""
    db: Optional[Session]
    user: Any  # Profile or MockProfile

    @property
    def is_admin(self) -> bool:
        return str(getattr(self.user, "role", "")).lower() in ("admin", "super_admin")

    @property
    def user_id(self) -> str:
        return str(getattr(self.user, "id", ""))

    @property
    def role(self) -> str:
        return str(getattr(self.user, "role", "user")).lower()

    @property
    def full_name(self) -> str:
        return str(getattr(self.user, "full_name", "Unknown User"))

    @property
    def warehouse_id(self) -> Optional[str]:
        wid = getattr(self.user, "warehouse_id", None)
        return str(wid) if wid else None


# ─── Full Database Schema ─────────────────────────────────────────────────────

DB_SCHEMAS: dict[str, str] = {
    "warehouses": "id, code, name, address, city, district, country, timezone, is_active, climate_zone, warehouse_type, metadata, created_at, updated_at",
    "departments": "id, warehouse_id, code, name, description, is_active, created_at, updated_at",
    "profiles": "id, employee_id, full_name, email, phone, role, status, warehouse_id, department_id, avatar_url, meta, created_at, updated_at",
    "assets": "id, asset_code, warehouse_id, department_id, asset_name, asset_type, category, vehicle_type, make, model, manufacture_year, registration_number, vin, status(ENUM: active|inactive|maintenance|retired|disposed — NOTE: assets do NOT have 'open' status; use 'active' for working assets), health_band, criticality_score, purchase_date, warranty_expiry_date, assigned_to, current_mileage, last_service_date, next_service_date, description, fuel_type, transmission, make_model, maintenance_priority, service_provider_type, metadata, created_by, vehicle_role, payload_capacity_kg, vehicle_age_years, lifetime_service_count, lifetime_breakdown_count, created_at, updated_at",
    "maintenance_events": "id, asset_id, event_type(ENUM: preventive|corrective|inspection|emergency), title, description, performed_by, scheduled_date, performed_at, odometer_reading, downtime_hours, cost_amount, currency, vendor_name, notes, metadata, created_at, updated_at",
    "sensor_readings": "id, asset_id, recorded_at, temperature, vibration, pressure, humidity, rpm, voltage, fuel_level, odometer, engine_hours_since_last_service, days_since_last_service, tire_health_pct, brake_health_pct, battery_health_pct, oil_life_pct, hydraulic_health_pct, vibration_rms_mm_s, fuel_efficiency_km_per_l, engine_hours_total, coolant_temp_max_c, battery_voltage_v, odometer_km",
    "tickets": "id, ticket_number, asset_id, warehouse_id, title, description, status(ENUM: open|in_progress|pending|resolved|closed|cancelled — NOTE: use 'open' for new/open tickets, 'in_progress' for active ones), priority(ENUM: low|medium|high), predicted_priority, final_priority, predicted_category(ENUM: electrical|mechanical|software), final_category, ticket_summary, created_by, assigned_to, reviewed_by, opened_at, reviewed_at, resolved_at, closed_at, created_at, updated_at",
    "prediction_runs": "id, model_id, asset_id, ticket_id, input_snapshot, requested_by, run_started_at, run_finished_at, status, error_message",
    "reports": "id, report_type, status, asset_id, warehouse_id, ticket_id, title, generated_by, report_text, report_json, file_path, generation_started_at, generation_completed_at, created_at",
    "notifications": "id, user_id, type, channel, title, message, status, related_asset_id, related_ticket_id, sent_at, read_at, created_at",
    "asset_assignments": "id, asset_id, user_id, assigned_by, assigned_at, unassigned_at, is_active, notes",
    "asset_status_history": "id, asset_id, old_status, new_status, changed_by, reason, created_at",
    "ticket_comments": "id, ticket_id, user_id, comment, is_internal, created_at",
    "ticket_status_history": "id, ticket_id, old_status, new_status, changed_by, note, created_at",
    "model_registry": "id, model_name, model_type, version, framework, artifact_path, metrics, is_active, created_at",
    # ML Prediction tables
    "asset_failure_predictions": "id, run_id, asset_id, health_score, failure_probability, confidence, risk_level, predicted_maintenance_date, days_until_maintenance, top_explanations, created_at",
    "asset_cost_predictions": "id, run_id, asset_id, estimated_cost, min_cost, max_cost, currency, confidence_score, created_at",
    "ticket_predictions": "id, run_id, ticket_id, predicted_category, predicted_priority, category_confidence, priority_confidence, generated_summary, created_at",
    "prediction_explanations": "id, run_id, asset_id, explanation_type, explanation_text, created_at",
    "prediction_feature_importance": "id, explanation_id, feature_name, feature_value, importance_score, direction, rank_order",
    "pdm_batch_predictions": "id, asset_id, failure_probability, maintenance_required, risk_level, predicted_days_until_maintenance, predicted_maintenance_date, health_score, health_status, contributing_factors, estimated_cost_lkr, min_cost_lkr, max_cost_lkr, top_explanations, predicted_at, run_duration_ms, status",
    "report_sources": "id, report_id, source_table, source_id, source_label, relevance_score, created_at",
}

# ─── Navigation Map ────────────────────────────────────────────────────────────

# Maps keywords to (instructions, route, button_label)
NAV_MAP: list[tuple[list[str], str, str, str]] = [
    (["password", "change password"], "To change your password:\n1️⃣ Click your avatar in the top-right corner.\n2️⃣ Select **Profile Settings**.\n3️⃣ Click **Change Password** and follow the prompts.", "/user/profile", "Go to Profile Settings"),
    (["profile", "settings", "account", "my settings"], "To view or edit your profile:\n1️⃣ Click your avatar in the top-right corner.\n2️⃣ Select **Profile Settings**.", "/user/profile", "Open Profile Settings"),
    (["dashboard", "home", "overview", "main page"], "The Dashboard is your main landing page after login. It shows live stats for assets, tickets, and fleet health.", "/admin/dashboard", "Go to Dashboard"),
    (["helpdesk", "help desk", "support ticket", "raise ticket", "create ticket", "new ticket"], "To create or manage support tickets:\n1️⃣ Click **Helpdesk** in the left sidebar.\n2️⃣ Click **New Ticket** to raise one.", "/admin/help-desk", "Go to Helpdesk"),
    # "ticket" / "tickets" is intentionally after helpdesk so helpdesk-specific phrases match first
    (["tickets", "ticket page", "open tickets", "view tickets", "my tickets"], "Here's the **Support Tickets** page where you can track, manage, and resolve all tickets.", "/admin/tickets", "Go to Tickets"),
    (["asset", "assets", "fleet", "vehicle", "vehicles", "open assets", "view assets"], "Here's the **Assets** section where you can view and manage all your assets and vehicles.", "/admin/assets", "Go to Assets"),
    (["report", "reports", "generate report", "view reports", "open reports"], "To generate reports:\n1️⃣ Click **Reports** in the left sidebar.\n2️⃣ Select the report type (Asset, Ticket, Prediction).\n3️⃣ Click **Generate**.", "/admin/reports", "Go to Reports"),
    (["warehouse", "warehouses", "location", "locations", "open warehouse"], "Here's the **Warehouse** section where you can manage all your warehouse locations.", "/admin/warehouses", "Go to Warehouses"),
    (["user", "users", "team", "staff", "manage users", "open users", "user management"], "Here's the **User Management** section where you can add, edit, or deactivate users.", "/admin/users", "Go to Users"),
    (["prediction", "predict", "failure prediction", "maintenance prediction", "predictive maintenance", "open predictions"], "To run AI predictions:\n1️⃣ Go to the **Assets** section.\n2️⃣ Open an asset and click **Run Prediction**.\nOr visit the **Reports** section to view all batch predictions.", "/admin/reports", "Go to Predictions / Reports"),
    (["cost", "cost estimation", "cost prediction", "maintenance cost"], "To view cost predictions:\n1️⃣ Go to the **Assets** section.\n2️⃣ Open any asset and view the **Cost Estimation** panel.\nOr visit **Reports** for batch cost reports.", "/admin/reports", "Go to Cost Reports"),
    (["notification", "notifications", "alerts", "open notifications"], "To view your notifications, click the 🔔 bell icon in the top navigation bar.", "/admin/notifications", "Go to Notifications"),
]


# ─── Zero-Token Handlers ──────────────────────────────────────────────────────

def handle_greeting(ctx: ToolContext) -> dict:
    """Returns instant greeting without any LLM call."""
    name = ctx.full_name.split()[0] if ctx.full_name else "there"
    menu = (
        f"👋 Hello, **{name}**! I'm **PredictiX Assistant**. Here's what I can help you with:\n\n"
        "📊 **Data & Analytics** — Ask about tickets, assets, users, warehouses\n"
        "🤖 **AI Predictions** — Failure probabilities, maintenance dates, cost estimations\n"
        "🧭 **Navigation** — *\"How do I change my password?\"*, *\"Where are reports?\"*\n"
        "❓ **FAQs** — Browse frequently asked questions\n"
        "📚 **Knowledge Base** — Policies, procedures, documentation\n"
        "👤 **Your Profile** — *\"Who am I?\"*, *\"What is my role?\"*\n\n"
        "Type **menu** anytime to see this again, or just ask your question!"
    )
    return {"answer": menu, "action_buttons": []}


def handle_whoami(ctx: ToolContext) -> dict:
    """Returns user profile without any LLM call."""
    user = ctx.user
    role = getattr(user, "role", "user")
    full_name = getattr(user, "full_name", "Unknown")
    email = getattr(user, "email", "N/A")
    employee_id = getattr(user, "employee_id", "N/A")
    status = getattr(user, "status", "active")
    wid = getattr(user, "warehouse_id", None)
    did = getattr(user, "department_id", None)

    lines = [
        f"👤 **Your Profile**\n",
        f"• **Name:** {full_name}",
        f"• **Email:** {email}",
        f"• **Role:** {role.replace('_', ' ').title()}",
        f"• **Employee ID:** {employee_id}",
        f"• **Status:** {'✅ Active' if status == 'active' else '❌ ' + status.title()}",
    ]
    if wid:
        lines.append(f"• **Warehouse ID:** {wid}")
    if did:
        lines.append(f"• **Department ID:** {did}")

    return {
        "answer": "\n".join(lines),
        "action_buttons": [{"label": "Go to My Profile", "path": "/user/profile"}],
    }


def handle_navigation(question: str, ctx: ToolContext) -> dict:
    """Returns navigation guidance and a clickable action button. 0 tokens."""
    q_lower = question.lower()
    for keywords, instruction, route, button_label in NAV_MAP:
        if any(kw in q_lower for kw in keywords):
            return {
                "answer": f"🧭 {instruction}\n\nPlease visit the Helpdesk section for more details. If you need further support, contact the admin at neuromindspredictix@gmail.com.",
                "action_buttons": [{"label": button_label, "path": route}],
            }
    # Generic fallback
    return {
        "answer": "🧭 You can navigate the system using the left sidebar:\n• **Dashboard** — Overview & live stats\n• **Assets** — Fleet management\n• **Helpdesk** — Tickets & support\n• **Reports** — AI predictions & analytics\n• **Users** — Team management\n• **Warehouses** — Location management",
        "action_buttons": [{"label": "Go to Dashboard", "path": "/admin/dashboard"}],
    }


def handle_faq(question: str, ctx: ToolContext) -> dict:
    """Fetch FAQs from Supabase, synthesize with LLM, and fallback to admin if not found."""
    from app.ai.services.llm_service import call_groq

    def _get_faq_fallback() -> dict:
        return {
            "answer": "Please reach out to our admins at **neuromindspredictix@gmail.com** and they'll get back to you as soon as possible.",
            "action_buttons": [{"label": "Copy Admin Email", "path": "copy:neuromindspredictix@gmail.com"}],
        }

    try:
        resp = (
            supabase.from_("faqs")
            .select("id,question,answer,category")
            .eq("is_active", True)
            .execute()
        )
        all_faqs = resp.data or []
    except Exception as e:
        log.warning("FAQ fetch failed: %s", e)
        all_faqs = []

    q_lower = question.lower()
    words = [w for w in q_lower.split() if len(w) > 2]
    scored = []
    for faq in all_faqs:
        faq_q = faq.get("question", "").lower()
        faq_a = faq.get("answer", "").lower()
        score = sum(2 for w in words if w in faq_q) + sum(1 for w in words if w in faq_a)
        if score > 0:
            scored.append((score, faq))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = [faq for _, faq in scored[:4]]

    if not top:
        return _get_faq_fallback()

    context_str = "\n".join(
        f"Q: {faq['question']}\nA: {faq['answer']}" for faq in top
    )
    user_name = ctx.full_name.split()[0] if ctx.full_name else "there"

    try:
        summary, fb = call_groq(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are PredictiX Assistant. Answer the user's question using ONLY the provided FAQ context. "
                        "CRITICAL INSTRUCTION: If the provided context does NOT contain the exact answer to the user's specific question (for example, they ask how to delete a ticket, but the context only explains how to open or view tickets), you MUST reply EXACTLY with the word: NOT_FOUND. Do not try to guess or invent an answer based on unrelated context. "
                        "If the context DOES answer the question accurately, be conversational, encouraging, and use simple language. "
                        "Never mention 'the FAQ', 'the context', or 'the database'. Just answer naturally. "
                        "Always start your response with a ✅ emoji and end with: '*Let me know if you need any more help! 😊*'"
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"My name is {user_name}. My question is: \"{question}\"\n\n"
                        f"FAQ Context:\n{context_str}"
                    ),
                },
            ],
            model="llama-3.1-8b-instant",
            max_tokens=400,
            temperature=0.1,
        )
        
        if not summary or "NOT_FOUND" in str(summary).strip():
            return _get_faq_fallback()
            
        answer = fb + str(summary)
    except Exception as e:
        log.error("FAQ LLM synthesis failed: %s", e)
        return _get_faq_fallback()

    return {
        "answer": answer,
        "action_buttons": [],
    }


def handle_knowledge(question: str, ctx: ToolContext) -> dict:
    """Semantic search on knowledge base, then summarize with fast model."""
    from app.ai.services.llm_service import call_groq

    results = search_knowledge(question, match_count=4)
    if not results:
        return {
            "answer": "📚 I couldn't find anything relevant in the knowledge base for that question. Try rephrasing or ask about a specific asset/ticket.",
            "action_buttons": [],
        }

    context_parts = [f"- {r.get('title', 'Article')}: {r.get('content', '')[:300]}" for r in results]
    context_str = "\n".join(context_parts)

    fallback_msg = ""
    try:
        summary, fallback_msg = call_groq(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are PredictiX Assistant. Summarize the following knowledge base articles to answer the user's question. "
                        "Be concise (3-5 sentences). Use professional language. End with 'Is there anything else I can help with?'"
                    ),
                },
                {"role": "user", "content": f"Question: {question}\n\nKnowledge Base:\n{context_str}"},
            ],
            model="llama-3.1-8b-instant",
            max_tokens=300,
            temperature=0.4,
        )
    except Exception as e:
        log.error("Knowledge summarization failed: %s", e)
        summary = context_str

    return {
        "answer": fallback_msg + f"📚 {summary}",
        "action_buttons": [],
    }


def handle_database(question: str, ctx: ToolContext) -> dict:
    """Two-agent pipeline: Table Selector → SQL Generator → Execute → Summarize."""
    from app.ai.services.llm_service import call_groq

    def _get_generic_fallback() -> dict:
        # Instead of just throwing an email, let the LLM try to answer it based on general persona
        try:
            ans, fb = call_groq(
                messages=[
                    {
                        "role": "system",
                        "content": "You are Sidekick, the PredictiX AI Assistant. The user asked a question that couldn't be answered via database search. "
                                   "Answer it based on general knowledge of the PredictiX Smart Asset Management System. "
                                   "Roles: Admins manage users, assets, and settings. Users can view assigned assets, create tickets, and run predictions. "
                                   "Keep it concise, friendly, and helpful. If you truly cannot answer it, tell them to contact neuromindspredictix@gmail.com."
                    },
                    {"role": "user", "content": question}
                ],
                model="llama-3.1-8b-instant",
                max_tokens=300,
                temperature=0.3,
            )
            if ans:
                return {"answer": fb + str(ans), "action_buttons": []}
        except Exception:
            pass
            
        return {
            "answer": "Please reach out to our admins at **neuromindspredictix@gmail.com** and they'll get back to you as soon as possible.",
            "action_buttons": [{"label": "Copy Admin Email", "path": "copy:neuromindspredictix@gmail.com"}],
        }

    # Collect fallback messages from models
    fallback_msg = ""

    # ── Step 0: Dashboard Fast-Path (100% UI Parity) ─────────────────────────
    q_lower = question.lower()
    is_summary = any(w in q_lower for w in ["summary", "overview", "dashboard stats", "all stats", "how many users", "total users", "how many tickets", "total tickets"])
    
    if is_summary:
        if ctx.role not in ["admin", "super_admin"]:
            return {
                "answer": "🔒 You do not have permission to view system-wide dashboard statistics. You can only view and manage your own tickets and assigned assets.",
                "action_buttons": [],
            }
        try:
            from app.routers.admin_dashboard import _build_admin_summary
            from app.models import Profile

            # Get exact dashboard KPIs
            summary_data = _build_admin_summary(ctx.db, ctx.warehouse_id)
            kpis = summary_data.get("kpis", {})

            # Get exact user counts matching the Users page logic
            users_q = ctx.db.query(Profile)
            if ctx.warehouse_id:
                users_q = users_q.filter((Profile.warehouse_id == ctx.warehouse_id) | (Profile.warehouse_id.is_(None)))
            all_users = users_q.all()

            total_users = len(all_users)
            active_users = sum(1 for u in all_users if getattr(u, "status", "").lower() == "active")
            admins = sum(1 for u in all_users if getattr(u, "role", "").lower() == "admin")
            super_admins = sum(1 for u in all_users if getattr(u, "role", "").lower() == "super_admin")
            regular_users = sum(1 for u in all_users if getattr(u, "role", "").lower() == "user")

            # Fake the SQL rows output so the Summarizer handles it perfectly
            rows = [
                {"Metric": "Total Users", "Count": total_users},
                {"Metric": "Active Users", "Count": active_users},
                {"Metric": "Admins", "Count": admins},
                {"Metric": "Super Admins", "Count": super_admins},
                {"Metric": "Regular Users", "Count": regular_users},
                {"Metric": "Total Assets", "Count": kpis.get("totalAssets", 0)},
                {"Metric": "Critical Alerts", "Count": kpis.get("criticalAlerts", 0)},
                {"Metric": "Open Tickets", "Count": kpis.get("openTickets", 0)},
                {"Metric": "High Priority Tickets", "Count": kpis.get("highPriorityTickets", 0)},
                {"Metric": "Predicted Failures", "Count": kpis.get("predictedFailures", 0)},
            ]
            
            # Jump straight to Step 4: Summarize
            selected_tables = ["users", "tickets", "assets", "dashboard"]
            sql = "DASHBOARD_FAST_PATH"
            goto_summarizer = True
        except Exception as e:
            log.error("Dashboard fast-path failed: %s", e)
            goto_summarizer = False
    else:
        goto_summarizer = False

    if not goto_summarizer:
        # ── Step 1: Table Selector (fast model) ──────────────────────────────────
        table_list = ", ".join(DB_SCHEMAS.keys())
        selector_prompt = (
            f"You are a database table selector for PredictiX (Smart Asset Management System).\n"
            f"The user asked: \"{question}\"\n\n"
            f"Available tables: {table_list}\n\n"
            "Respond with ONLY a comma-separated list of up to 4 table names that are needed to answer this question. "
            "No explanations, no other text."
        )
        try:
            raw_tables, fb = call_groq(
                messages=[{"role": "user", "content": selector_prompt}],
                model="llama-3.1-8b-instant",
                max_tokens=60,
                temperature=0.1,
            )
            if fb and not fallback_msg: fallback_msg = fb
            selected_tables = [t.strip() for t in str(raw_tables).split(",") if t.strip() in DB_SCHEMAS]
        except Exception as e:
            log.error("Table selector failed: %s", e)
            selected_tables = ["tickets", "assets"]

        if not selected_tables:
            selected_tables = ["tickets", "assets"]

        # ── Step 2: SQL Generator (heavy model) ──────────────────────────────────
        schema_str = "\n".join(
            f"Table '{t}': columns → {DB_SCHEMAS[t]}" for t in selected_tables
        )

        # Build role-based scoping instruction
        if ctx.is_admin:
            scope_instruction = "The current user is an ADMIN. You may query ALL records across the entire system."
            if ctx.warehouse_id:
                scope_instruction += f" The admin is scoped to warehouse_id = '{ctx.warehouse_id}'."
        else:
            scope_instruction = (
                f"The current user is a STANDARD USER (id='{ctx.user_id}'). "
                "You MUST add a WHERE clause to only show records where created_by = '{user_id}' OR assigned_to = '{user_id}'. "
                "Never expose other users' private data."
            ).replace("{user_id}", ctx.user_id)
            role_instructions = "\nSECURITY RULE: The user is an admin. They have full access to all data."

        sql_prompt = (
            f"You are a PostgreSQL expert. Write a query to answer: \"{question}\"\n"
            f"Use ONLY these tables: {selected_tables}\n"
            f"Schema:\n{schema_str}\n"
            f"{role_instructions}\n"
            "Respond ONLY with raw valid PostgreSQL SQL. No markdown formatting, no backticks, no explanations. "
            "If the question cannot be answered using the schema, or violates the security rule, output EXACTLY: 'ERROR: reason'"
        )

        try:
            raw_sql, fb = call_groq(
                messages=[{"role": "user", "content": sql_prompt}],
                model="llama-3.3-70b-versatile",
                max_tokens=350,
                temperature=0.1,
            )
            if fb and not fallback_msg: fallback_msg = fb
            sql = str(raw_sql).strip().lstrip("```sql").lstrip("```").rstrip("```").strip()
        except Exception as e:
            log.error("SQL generator failed: %s", e)
            return {"answer": "⚠️ I had trouble generating a database query. Please try again shortly.", "action_buttons": []}

        if sql.startswith("ERROR: Permission Denied"):
            return {
                "answer": "🔒 You do not have permission to view system-wide data. You can only view records assigned to or created by you.",
                "action_buttons": [],
            }

        if sql.startswith("ERROR:"):
            return _get_generic_fallback()

        # Security guard: block any mutation
        import re
        sql_upper = sql.upper()
        for dangerous in ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "TRUNCATE", "GRANT"]:
            if re.search(rf"\b{dangerous}\b", sql_upper):
                return _get_generic_fallback()

        # ── Step 3: Execute (with self-healing retry on DB error) ────────────────
        if ctx.db is None:
            return {"answer": "⚠️ Database is not available right now. Please try again in a moment.", "action_buttons": []}

        def _run_sql(sql_to_run: str):
            result = ctx.db.execute(text(sql_to_run)).fetchall()
            if not result:
                return None
            keys = list(result[0]._mapping.keys())
            return [dict(zip(keys, row)) for row in result[:50]]

        rows = None
        try:
            rows = _run_sql(sql)
        except Exception as first_err:
            log.warning("SQL execution failed (attempt 1): %s | SQL: %s", first_err, sql)
            ctx.db.rollback()
            # Self-healing: feed the error back to the LLM to fix the SQL
            try:
                fix_prompt = (
                    f"The following PostgreSQL query failed with this error:\n"
                    f"ERROR: {str(first_err)[:300]}\n\n"
                    f"FAILED SQL:\n{sql}\n\n"
                    f"SCHEMA (correct ENUM values):\n{schema_str}\n\n"
                    "Fix the SQL query. Common fixes:\n"
                    "- assets.status valid values: active, inactive, maintenance, retired, disposed (NOT 'open')\n"
                    "- tickets.status valid values: open, in_progress, pending, resolved, closed, cancelled\n"
                    "- Use CAST if comparing text with enum column\n"
                    "Output ONLY the corrected raw SQL. No markdown, no backticks."
                )
                corrected_sql_raw, _ = call_groq(
                    messages=[{"role": "user", "content": fix_prompt}],
                    model="llama-3.3-70b-versatile",
                    max_tokens=350,
                    temperature=0.1,
                )
                corrected_sql = str(corrected_sql_raw).strip().lstrip("```sql").lstrip("```").rstrip("```").strip()
                log.info("Self-healed SQL: %s", corrected_sql)
                rows = _run_sql(corrected_sql)
                sql = corrected_sql  # update for logging
            except Exception as second_err:
                log.error("SQL self-healing also failed: %s", second_err)
                ctx.db.rollback()
                return {
                    "answer": "⚠️ I couldn't retrieve the data for your query. The database may be temporarily unavailable or the question needs rephrasing. Try being more specific!",
                    "action_buttons": [],
                }

        if rows is None:
            return {"answer": "📊 The query ran successfully but returned no results. The data matching your request may not exist yet.", "action_buttons": []}

    # ── Step 4: Summarize (fast model) ───────────────────────────────────────
    row_str = str(rows[:30])  # cap context to keep tokens low

    # Build a direct plain-text fallback from the raw rows (used if LLM fails)
    def _build_fallback(rows: list[dict]) -> str:
        if not rows:
            return "📊 No data found."
        lines = [f"📊 **Results ({len(rows)} record{'s' if len(rows) != 1 else ''}):**\n"]
        for row in rows:
            keys = list(row.keys())
            # Clean format for two-column stats (e.g. Metric/Count, Category/Total)
            if len(keys) == 2 and str(keys[1]).lower() in ["count", "value", "total", "amount", "sum"]:
                lines.append(f"• **{row[keys[0]]}:** {row[keys[1]]}")
            else:
                line_parts = []
                for k, v in row.items():
                    if v is not None and str(v).strip():
                        pretty_key = str(k).replace("_", " ").title()
                        line_parts.append(f"**{pretty_key}:** {v}")
                lines.append("• " + " | ".join(line_parts))
        return "\n".join(lines)

    summarizer_prompt = (
        f"You are PredictiX Assistant. A user asked: \"{question}\"\n"
        f"The database returned this data: {row_str}\n\n"
        "INSTRUCTIONS — follow these EXACTLY:\n"
        "1. Start with a ONE-LINE summary stating the TOTAL count.\n"
        "2. Then list EVERY SINGLE category/group/status/role from the data with its exact count.\n"
        "   Format each line as: [emoji] **Category Name:** X items\n"
        "3. Use 👥 for user roles, 🎫 for ticket status, ⚙️ for asset types, 📊 for general stats.\n"
        "4. Quote EXACT numbers — never round or approximate.\n"
        "5. Never say 'Found N records matching' — always show the actual breakdown.\n"
        "6. Never expose raw UUIDs.\n"
        "7. End with a polite, helpful closing sentence."
    )
    try:
        summary, fb = call_groq(
            messages=[{"role": "user", "content": summarizer_prompt}],
            model="llama-3.1-8b-instant",
            max_tokens=400,
            temperature=0.2,
        )
        if fb and not fallback_msg: fallback_msg = fb
        if not summary or len(str(summary).strip()) < 10:
            summary = _build_fallback(rows)
    except Exception as e:
        log.error("Summarizer failed: %s", e)
        summary = _build_fallback(rows)

    # Determine interactive action buttons based on queried tables
    action_buttons = []
    if "profiles" in selected_tables or "users" in selected_tables:
        action_buttons.append({"label": "Manage Users", "path": "/admin/users"})
    if "tickets" in selected_tables:
        action_buttons.append({"label": "View Tickets", "path": "/admin/tickets"})
    if "assets" in selected_tables:
        action_buttons.append({"label": "View Assets", "path": "/admin/assets"})
    if "warehouses" in selected_tables:
        action_buttons.append({"label": "View Warehouses", "path": "/admin/warehouse"})

    # Limit to 2 buttons max so it doesn't clutter the UI
    action_buttons = action_buttons[:2]

    return {
        "answer": fallback_msg + str(summary),
        "action_buttons": action_buttons,
    }



def handle_prediction_info(question: str, ctx: ToolContext) -> dict:
    """Handles questions about how to USE prediction models + shows predictions data."""
    q_lower = question.lower()

    # If the user wants to KNOW HOW to use the models → give guidance + button
    how_to_keywords = ["how", "how to", "use", "run", "generate", "where", "start", "launch"]
    is_how_to = any(kw in q_lower for kw in how_to_keywords)

    if is_how_to and "predict" in q_lower or "report" in q_lower or "cost estimat" in q_lower:
        answer = (
            "🤖 **AI Prediction Models in PredictiX:**\n\n"
            "**🔮 Failure Prediction (Predictive Maintenance)**\n"
            "• Go to any Asset → Click **Run Prediction** → The AI calculates failure probability, health score, and predicted maintenance date.\n\n"
            "**💰 Cost Estimation**\n"
            "• Go to **Reports** → Select **Cost Prediction** → Choose an asset or warehouse to estimate maintenance costs.\n\n"
            "**🎫 Ticket AI Classification**\n"
            "• When creating or viewing a ticket, the AI automatically predicts its category and priority.\n\n"
            "**📦 Batch Predictions (PDM)**\n"
            "• Go to **Reports** → Select **Batch PDM** to run predictions for all assets at once.\n\n"
            "Please visit the Helpdesk section for more details. Contact admin at neuromindspredictix@gmail.com."
        )
        buttons = [
            {"label": "Go to Reports / Predictions", "path": "/admin/reports"},
            {"label": "Go to Assets", "path": "/admin/assets"},
        ]
        return {"answer": answer, "action_buttons": buttons}

    # Otherwise, query the actual prediction data from DB
    return handle_database(question, ctx)
