"""PredictiX Chatbot – Pure-Python Tool Handlers & Zero-Token Handlers.

Architecture:
  - Zero-Token handlers: Greeting, Navigation, WhoAmI, FAQ
    → No LLM call at all. Instant, deterministic responses.
  - Database handler: executes SQL generated by a sub-agent
  - Knowledge handler: semantic search on the knowledge base
  - Prediction handler: queries all ML prediction tables
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Optional

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.db.supabase_client import supabase

log = logging.getLogger("predictix.tools")


# ─── Context ─────────────────────────────────────────────────────────────────

@dataclass
class ToolContext:
    """Per-request context handed to every handler."""
    db: Optional[Session]
    user: Any  # Profile or MockProfile
    frontend_context: Optional[dict] = None

    @property
    def is_admin(self) -> bool:
        return str(getattr(self.user, "role", "")).lower() in ("admin", "super_admin")

    @property
    def user_id(self) -> str:
        return str(getattr(self.user, "id", ""))

    @property
    def role(self) -> str:
        return str(getattr(self.user, "role", "user")).lower()

    @property
    def full_name(self) -> str:
        return str(getattr(self.user, "full_name", "Unknown User"))

    @property
    def warehouse_id(self) -> Optional[str]:
        wid = getattr(self.user, "warehouse_id", None)
        return str(wid) if wid else None


# ─── Full Database Schema ─────────────────────────────────────────────────────

DB_SCHEMAS: dict[str, str] = {
    "warehouses": "id, code, name, address, city, district, country, timezone, is_active, climate_zone, warehouse_type, metadata, created_at, updated_at",
    "departments": "id, warehouse_id, code, name, description, is_active, created_at, updated_at",
    "profiles": "id, employee_id, full_name, email, phone, role(ENUM: admin|super_admin|user), status(ENUM: active|inactive|suspended), warehouse_id, department_id, avatar_url, meta, created_at, updated_at",
    "assets": "id, asset_code, warehouse_id, department_id, asset_name, asset_type, category(e.g. Heavy Truck (16T), Forklift 2.5T, Delivery Van (1.5T), Medium Truck (7T), Light Truck (3.5T), Mini Truck (1T)), vehicle_type, make, model, manufacture_year, registration_number, vin, status(ENUM: active|inactive|under_maintenance|decommissioned), health_band(ENUM: excellent|good|moderate|poor|critical), criticality_score(float 0-100), purchase_date, warranty_expiry_date, assigned_to, current_mileage, last_service_date, next_service_date, description, fuel_type, transmission, make_model, maintenance_priority, created_at, updated_at",
    "maintenance_events": "id, asset_id, event_type(ENUM: preventive|corrective|inspection|emergency), title, description, performed_by, scheduled_date, performed_at, odometer_reading, downtime_hours, cost_amount, currency, vendor_name, notes, metadata, created_at, updated_at",
    "sensor_readings": "id, asset_id, recorded_at, temperature, vibration, pressure, humidity, rpm, voltage, fuel_level, odometer, engine_hours_since_last_service, days_since_last_service, tire_health_pct, brake_health_pct, battery_health_pct, oil_life_pct, hydraulic_health_pct, vibration_rms_mm_s, fuel_efficiency_km_per_l, engine_hours_total, coolant_temp_max_c, battery_voltage_v, odometer_km",
    "tickets": "id, ticket_number, asset_id, warehouse_id, title, description, status(ENUM: open|in_progress|resolved|closed), priority(ENUM: low|medium|high), predicted_priority, final_priority, predicted_category(ENUM: electrical|mechanical|software), final_category(ENUM: electrical|mechanical|software), ticket_summary, created_by, assigned_to, reviewed_by, opened_at, reviewed_at, resolved_at, closed_at, created_at, updated_at",
    "prediction_runs": "id, model_id, asset_id, ticket_id, input_snapshot, requested_by, run_started_at, run_finished_at, status, error_message",
    "reports": "id, report_type, status, asset_id, warehouse_id, ticket_id, title, generated_by, report_text, report_json, file_path, generation_started_at, generation_completed_at, created_at",
    "notifications": "id, user_id, type, channel, title, message, status, related_asset_id, related_ticket_id, sent_at, read_at, created_at",
    "asset_assignments": "id, asset_id, user_id, assigned_by, assigned_at, unassigned_at, is_active, notes",
    "asset_status_history": "id, asset_id, old_status, new_status, changed_by, reason, created_at",
    "ticket_comments": "id, ticket_id, user_id, comment, is_internal, created_at",
    "ticket_status_history": "id, ticket_id, old_status, new_status, changed_by, note, created_at",
    "model_registry": "id, model_name, model_type, version, framework, artifact_path, metrics, is_active, created_at",
    "pdm_batch_predictions": "id, asset_id, failure_probability(float 0.0-1.0), maintenance_required(boolean), risk_level(ENUM: low|medium|high|critical), predicted_days_until_maintenance(int), predicted_maintenance_date(date), health_score(float 0-100), health_status(ENUM: excellent|good|moderate|poor|critical), contributing_factors, estimated_cost_lkr(float), min_cost_lkr, max_cost_lkr, top_explanations, predicted_at, run_duration_ms, status(ok) — PRIMARY TABLE for ML predictions, health scores, and critical assets",
    "report_sources": "id, report_id, source_table, source_id, source_label, relevance_score, created_at",
}

# ─── Navigation Map ────────────────────────────────────────────────────────────

# Maps keywords to (instructions, route, button_label)
NAV_MAP: list[tuple[list[str], str, str, str]] = [
    (["password", "change password"], "To change your password:\n1️⃣ Click your avatar in the top-right corner.\n2️⃣ Select **Profile Settings**.\n3️⃣ Click **Change Password** and follow the prompts.", "/user/profile", "Go to Profile Settings"),
    (["profile", "settings", "account", "my settings"], "To view or edit your profile:\n1️⃣ Click your avatar in the top-right corner.\n2️⃣ Select **Profile Settings**.", "/user/profile", "Open Profile Settings"),
    (["dashboard", "home", "overview", "main page"], "The Dashboard is your main landing page after login. It shows live stats for assets, tickets, and fleet health.", "/admin/dashboard", "Go to Dashboard"),
    (["helpdesk", "help desk", "support ticket", "raise ticket", "create ticket", "new ticket"], "To create or manage support tickets:\n1️⃣ Click **Helpdesk** in the left sidebar.\n2️⃣ Click **New Ticket** to raise one.", "/admin/help-desk", "Go to Helpdesk"),
    # "ticket" / "tickets" is intentionally after helpdesk so helpdesk-specific phrases match first
    (["tickets", "ticket page", "open tickets", "view tickets", "my tickets"], "Here's the **Support Tickets** page where you can track, manage, and resolve all tickets.", "/admin/tickets", "Go to Tickets"),
    (["asset", "assets", "fleet", "vehicle", "vehicles", "open assets", "view assets"], "Here's the **Assets** section where you can view and manage all your assets and vehicles.", "/admin/assets", "Go to Assets"),
    (["report", "reports", "generate report", "view reports", "open reports"], "To generate reports:\n1️⃣ Click **Reports** in the left sidebar.\n2️⃣ Select the report type (Asset, Ticket, Prediction).\n3️⃣ Click **Generate**.", "/admin/reports", "Go to Reports"),
    (["warehouse", "warehouses", "location", "locations", "open warehouse"], "Here's the **Warehouse** section where you can manage all your warehouse locations.", "/admin/warehouses", "Go to Warehouses"),
    (["user", "users", "team", "staff", "manage users", "open users", "user management"], "Here's the **User Management** section where you can add, edit, or deactivate users.", "/admin/users", "Go to Users"),
    (["prediction", "predict", "failure prediction", "maintenance prediction", "predictive maintenance", "open predictions"], "To run AI predictions:\n1️⃣ Go to the **Assets** section.\n2️⃣ Open an asset and click **Run Prediction**.\nOr visit the **Reports** section to view all batch predictions.", "/admin/reports", "Go to Predictions / Reports"),
    (["cost", "cost estimation", "cost prediction", "maintenance cost"], "To view cost predictions:\n1️⃣ Go to the **Assets** section.\n2️⃣ Open any asset and view the **Cost Estimation** panel.\nOr visit **Reports** for batch cost reports.", "/admin/reports", "Go to Cost Reports"),
    (["notification", "notifications", "alerts", "open notifications"], "To view your notifications, click the 🔔 bell icon in the top navigation bar.", "/admin/notifications", "Go to Notifications"),
]


# ─── Zero-Token Handlers ──────────────────────────────────────────────────────

def handle_greeting(ctx: ToolContext) -> dict:
    """Returns instant greeting without any LLM call."""
    name = ctx.full_name.split()[0] if ctx.full_name else "there"
    menu = (
        f"👋 Hello, **{name}**! I'm **PredictiX Assistant**. Here's what I can help you with:\n\n"
        "📊 **Data & Analytics** — Ask about tickets, assets, users, warehouses\n"
        "🤖 **AI Predictions** — Failure probabilities, maintenance dates, cost estimations\n"
        "🧭 **Navigation** — *\"How do I change my password?\"*, *\"Where are reports?\"*\n"
        "❓ **FAQs** — Browse frequently asked questions\n"
        "📚 **Knowledge Base** — Policies, procedures, documentation\n"
        "👤 **Your Profile** — *\"Who am I?\"*, *\"What is my role?\"*\n\n"
        "Type **menu** anytime to see this again, or just ask your question!"
    )
    return {"answer": menu, "action_buttons": []}


def handle_whoami(ctx: ToolContext) -> dict:
    """Returns user profile without any LLM call."""
    user = ctx.user
    role = getattr(user, "role", "user")
    full_name = getattr(user, "full_name", "Unknown")
    email = getattr(user, "email", "N/A")
    employee_id = getattr(user, "employee_id", "N/A")
    status = getattr(user, "status", "active")
    wid = getattr(user, "warehouse_id", None)
    did = getattr(user, "department_id", None)

    lines = [
        f"👤 **Your Profile**\n",
        f"• **Name:** {full_name}",
        f"• **Email:** {email}",
        f"• **Role:** {role.replace('_', ' ').title()}",
        f"• **Employee ID:** {employee_id}",
        f"• **Status:** {'✅ Active' if status == 'active' else '❌ ' + status.title()}",
    ]
    if wid:
        lines.append(f"• **Warehouse ID:** {wid}")
    if did:
        lines.append(f"• **Department ID:** {did}")

    return {
        "answer": "\n".join(lines),
        "action_buttons": [{"label": "Go to My Profile", "path": "/user/profile"}],
    }


def handle_navigation(question: str, ctx: ToolContext) -> dict:
    """Returns navigation guidance and a clickable action button. 0 tokens."""
    q_lower = question.lower()
    for keywords, instruction, route, button_label in NAV_MAP:
        if any(kw in q_lower for kw in keywords):
            return {
                "answer": f"🧭 {instruction}\n\nPlease visit the Helpdesk section for more details. If you need further support, contact the admin at neuromindspredictix@gmail.com.",
                "action_buttons": [{"label": button_label, "path": route}],
            }
    # Generic fallback
    return {
        "answer": "🧭 You can navigate the system using the left sidebar:\n• **Dashboard** — Overview & live stats\n• **Assets** — Fleet management\n• **Helpdesk** — Tickets & support\n• **Reports** — AI predictions & analytics\n• **Users** — Team management\n• **Warehouses** — Location management",
        "action_buttons": [{"label": "Go to Dashboard", "path": "/admin/dashboard"}],
    }


def handle_faq(question: str, ctx: ToolContext) -> dict:
    """Fetch FAQs from Supabase, synthesize with LLM, and fallback to admin if not found."""
    from app.ai.services.llm_service import call_groq

    def _get_faq_fallback() -> dict:
        return {
            "answer": "Please reach out to our admins at **neuromindspredictix@gmail.com** and they'll get back to you as soon as possible.",
            "action_buttons": [{"label": "Copy Admin Email", "path": "copy:neuromindspredictix@gmail.com"}],
        }

    try:
        resp = (
            supabase.from_("faqs")
            .select("id,question,answer,category")
            .eq("is_active", True)
            .execute()
        )
        all_faqs = resp.data or []
    except Exception as e:
        log.warning("FAQ fetch failed: %s", e)
        all_faqs = []

    q_lower = question.lower()
    words = [w for w in q_lower.split() if len(w) > 2]
    scored = []
    for faq in all_faqs:
        faq_q = faq.get("question", "").lower()
        faq_a = faq.get("answer", "").lower()
        score = sum(2 for w in words if w in faq_q) + sum(1 for w in words if w in faq_a)
        if score > 0:
            scored.append((score, faq))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = [faq for _, faq in scored[:4]]

    if not top:
        return handle_knowledge(question, ctx)

    context_str = "\n".join(
        f"Q: {faq['question']}\nA: {faq['answer']}" for faq in top
    )
    user_name = ctx.full_name.split()[0] if ctx.full_name else "there"

    try:
        summary, fb = call_groq(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are PredictiX Assistant. Answer the user's question using ONLY the provided FAQ context. "
                        "CRITICAL INSTRUCTION: If the provided context does NOT contain the exact answer to the user's specific question (for example, they ask how to delete a ticket, but the context only explains how to open or view tickets), you MUST reply EXACTLY with the word: NOT_FOUND. Do not try to guess or invent an answer based on unrelated context. "
                        "If the context DOES answer the question accurately, be conversational, encouraging, and use simple language. "
                        "Never mention 'the FAQ', 'the context', or 'the database'. Just answer naturally. "
                        "Always start your response with a ✅ emoji and end with: '*Let me know if you need any more help! 😊*'"
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"My name is {user_name}. My question is: \"{question}\"\n\n"
                        f"FAQ Context:\n{context_str}"
                    ),
                },
            ],
            max_tokens=400,
            temperature=0.1,
        )
        
        if not summary or "NOT_FOUND" in str(summary).strip():
            return handle_knowledge(question, ctx)
            
        answer = fb + str(summary)
    except Exception as e:
        log.error("FAQ LLM synthesis failed: %s", e)
        return handle_knowledge(question, ctx)

    return {
        "answer": answer,
        "action_buttons": [],
    }


def handle_knowledge(question: str, ctx: ToolContext) -> dict:
    """Semantic search on knowledge base, then synthesize and format cleanly with fast model."""
    from app.ai.services.llm_service import call_groq
    from app.chatbot.knowledge_service import search_knowledge

    raw_results = search_knowledge(question, match_count=4)
    if not raw_results:
        return {
            "answer": "📚 I couldn't find anything relevant in the knowledge base for that question. Try rephrasing or ask about a specific asset/ticket.",
            "action_buttons": [],
        }

    # Filter out low-similarity noisy matches (keep only relevant results with similarity >= 0.20)
    filtered = [r for r in raw_results if r.get("similarity", 0) >= 0.20]
    results = filtered if filtered else [raw_results[0]]

    context_parts = [
        f"Article Title: {r.get('title', 'Article')}\nContent: {r.get('content', '')}"
        for r in results
    ]
    context_str = "\n\n".join(context_parts)

    fallback_msg = ""
    try:
        summary, fallback_msg = call_groq(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are PredictiX Assistant. Answer the user's question directly using ONLY the provided Knowledge Base articles.\n\n"
                        "CRITICAL FORMATTING INSTRUCTIONS:\n"
                        "1. Focus ONLY on the article that directly answers the question. Ignore any unrelated background articles.\n"
                        "2. Format the response with clean, professional line breaks and spacing. Use bold titles, bullet points, or numbered steps for instructions.\n"
                        "3. Do NOT dump raw lists of article titles or unformatted bullet points.\n"
                        "4. Do NOT include general fleet statistics, counts of critical assets, or predicted failures unless explicitly asked.\n"
                        "5. Start your response with an appropriate professional emoji (e.g., 👤 for profile/account, ⚙️ for assets, 🎫 for tickets, 📚 for guides, 💡 for tips).\n"
                        "6. End with a polite closing, e.g. '*Let me know if you need any more help! 😊*'"
                    ),
                },
                {"role": "user", "content": f"User Question: \"{question}\"\n\nKnowledge Base Articles:\n{context_str}"},
            ],
            max_tokens=400,
            temperature=0.2,
        )
        if summary:
            return {
                "answer": fallback_msg + str(summary).strip(),
                "action_buttons": [],
            }
    except Exception as e:
        log.error("Knowledge summarization failed: %s", e)

    # Fallback to single top article with clean formatting if LLM fails
    top_art = results[0]
    clean_ans = f"📚 **{top_art.get('title', 'Knowledge Article')}**\n\n{top_art.get('content', '')}\n\n*Let me know if you need any more help! 😊*"
    return {
        "answer": fallback_msg + clean_ans,
        "action_buttons": [],
    }


def handle_database(question: str, ctx: ToolContext) -> dict:
    """Two-agent pipeline: Table Selector → SQL Generator → Execute → Summarize."""
    from app.ai.services.llm_service import call_groq

    def _get_generic_fallback() -> dict:
        # Instead of just throwing an email, let the LLM try to answer it based on general persona
        try:
            ans, fb = call_groq(
                messages=[
                    {
                        "role": "system",
                        "content": "You are Sidekick, the PredictiX AI Assistant. The user asked a question that couldn't be answered via database search. "
                                   "Answer it based on general knowledge of the PredictiX Smart Asset Management System. "
                                   "Do NOT include general fleet statistics, counts of critical assets, or predicted failures (e.g. '205 assets at critical risk', '125 predicted to fail') unless the user's question explicitly asks for numbers, counts, or statistics. "
                                   "Use professional emojis strategically to format your response (e.g., 📊 for stats, 🎫 for tickets, ⚙️ for assets, 👥 for users, 💡 for suggestions, ⚠️ for alerts). "
                                   "Roles: Admins manage users, assets, and settings. Users can view assigned assets, create tickets, and run predictions. "
                                   "Keep it concise, friendly, and helpful. If you truly cannot answer it, tell them to contact neuromindspredictix@gmail.com."
                    },
                    {"role": "user", "content": question}
                ],
                max_tokens=300,
                temperature=0.3,
            )
            if ans:
                return {"answer": fb + str(ans), "action_buttons": []}
        except Exception as exc:
            # Swallowed on purpose — the caller still gets the contact-admin
            # reply below — but never silently: a persistently failing LLM here
            # is invisible otherwise, since the user just sees a polite message.
            log.warning("Generic chatbot fallback could not reach the LLM: %s", exc)
        return {
            # The trailing "(Debug: Generic fallback hit)" that used to be here
            # was shipped verbatim to end users in the chat window.
            "answer": (
                "I couldn't find an answer to that in your fleet data. "
                "Please reach out to our admins at **neuromindspredictix@gmail.com** "
                "and they'll get back to you as soon as possible."
            ),
            "action_buttons": [{"label": "Copy Admin Email", "path": "copy:neuromindspredictix@gmail.com"}],
        }

    def _get_contextual_fallback(error_reason: str) -> dict:
        fc = getattr(ctx, "frontend_context", None)
        if fc:
            try:
                ans, fb = call_groq(
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are Sidekick, the PredictiX AI Assistant. "
                                "We had trouble querying the database directly, but we have this cached frontend dashboard state: "
                                f"{str(fc)}\n\n"
                                "Answer the user's question as best as you can using only this cached data. Keep it friendly, helpful, and concise. "
                                "Do NOT mention 'frontend context', 'cached data', 'database errors', or 'SQL'. Just answer the question naturally. "
                                "Do NOT include general fleet statistics, counts of critical assets, or predicted failures from the cached state (e.g. '205 assets at critical risk', '125 predicted to fail') unless the user's question explicitly asks for numbers, counts, or statistics. "
                                "Use professional emojis strategically to format your response (e.g., 📊 for stats, 🎫 for tickets, ⚙️ for assets, 👥 for users, 💡 for suggestions, ⚠️ for alerts). "
                                "If you cannot answer the question using the provided state, say: 'The database is temporarily busy, but you can find this information on the main dashboard page.'"
                            )
                        },
                        {"role": "user", "content": question}
                    ],
                    max_tokens=300,
                    temperature=0.3,
                )
                if ans:
                    return {"answer": fb + str(ans), "action_buttons": []}
            except Exception as e:
                log.error("Failed to generate contextual fallback: %s", e)

        return {
            "answer": "⚠️ The database is temporarily busy. You can find this information on the dashboard or relevant asset/ticket pages using the navigation buttons below.",
            "action_buttons": [
                {"label": "Go to Dashboard", "path": "/admin/dashboard"},
                {"label": "View Assets", "path": "/admin/assets"},
            ],
        }

    # Collect fallback messages from models
    fallback_msg = ""
    q_lower = question.lower()

    # ── Fast-Path A: Critical Asset Lookups ───────────────────────────────────
    if any(k in q_lower for k in ["critical asset", "most critical", "highest risk", "most at risk", "urgent asset", "lowest health"]):
        try:
            if ctx.role not in ["admin", "super_admin"]:
                query = ctx.db.execute(text(
                    "SELECT a.asset_name, a.asset_code, a.category, a.vehicle_type, a.status, a.health_band, "
                    "p.failure_probability, p.health_score, p.risk_level, p.predicted_maintenance_date "
                    "FROM assets a JOIN pdm_batch_predictions p ON a.id = p.asset_id "
                    "WHERE a.assigned_to = :uid "
                    "ORDER BY p.failure_probability DESC, p.health_score ASC LIMIT 1"
                ), {"uid": ctx.user_id}).mappings().first()
                if not query:
                    return {
                        "answer": "⚙️ You currently have no critical assets assigned to you.",
                        "action_buttons": [{"label": "View My Assets", "path": "/user/assets"}]
                    }
            else:
                sql_str = (
                    "SELECT a.asset_name, a.asset_code, a.category, a.vehicle_type, a.status, a.health_band, "
                    "p.failure_probability, p.health_score, p.risk_level, p.predicted_maintenance_date "
                    "FROM assets a JOIN pdm_batch_predictions p ON a.id = p.asset_id "
                )
                params = {}
                if ctx.warehouse_id:
                    sql_str += " WHERE a.warehouse_id = :wid "
                    params["wid"] = ctx.warehouse_id
                sql_str += " ORDER BY p.failure_probability DESC, p.health_score ASC LIMIT 1"
                query = ctx.db.execute(text(sql_str), params).mappings().first()
            
            if query:
                fail_pct = round(float(query['failure_probability'] or 0) * 100, 1) if query['failure_probability'] is not None else 0
                health_sc = round(float(query['health_score'] or 0), 1) if query['health_score'] is not None else 0
                ans = (
                    f"⚙️ **Most Critical Asset: {query['asset_name']} [{query['asset_code']}]**\n\n"
                    f"• **Category:** {query['category'] or query['vehicle_type'] or 'Fleet Asset'}\n"
                    f"• **Current Status:** {str(query['status']).replace('_', ' ').title()}\n"
                    f"• **Health Band:** ⚠️ {str(query['health_band']).upper()}\n"
                    f"• **Health Score:** {health_sc}%\n"
                    f"• **Failure Probability:** 🚨 {fail_pct}%\n"
                    f"• **Risk Level:** {str(query['risk_level']).title()}\n"
                    f"• **Predicted Maintenance:** {query['predicted_maintenance_date'] or 'Immediate inspection recommended'}\n\n"
                    f"*Action recommended: Schedule immediate maintenance inspection.*"
                )
                return {
                    "answer": ans,
                    "action_buttons": [
                        {"label": f"View {query['asset_code']}", "path": f"/admin/assets/{query['asset_code']}"},
                        {"label": "Assets Dashboard", "path": "/admin/assets"}
                    ]
                }
        except Exception as e:
            log.error("Critical asset fast-path failed: %s", e)

    # ── Fast-Path B: Category Breakdown & Count Queries ───────────────────────
    breakdown_triggers = [
        "how many ticket", "how many asset", "how many user", "number of ticket", "number of asset",
        "number of user", "total ticket", "total asset", "total user", "count of ticket", "count of asset",
        "count of user", "by category", "by sub category", "by sub categories", "by status", "by priority",
        "by role", "by health", "breakdown", "all sub categories"
    ]
    is_count_breakdown = any(t in q_lower for t in breakdown_triggers)

    if is_count_breakdown:
        try:
            # 1. Standard User Scoping
            if ctx.role not in ["admin", "super_admin"]:
                if "user" in q_lower and not ("ticket" in q_lower or "asset" in q_lower):
                    return {
                        "answer": "🔒 You do not have permission to view team user accounts. You can only view your own profile and assigned tickets.",
                        "action_buttons": [{"label": "My Profile", "path": "/user/profile"}]
                    }
                
                # User's tickets
                user_tickets = ctx.db.execute(text(
                    "SELECT status, count(*) FROM tickets WHERE created_by = :uid OR assigned_to = :uid GROUP BY status"
                ), {"uid": ctx.user_id}).fetchall()
                total_t = sum(c for _, c in user_tickets)
                
                t_lines = [f"• **{str(s).replace('_', ' ').title()}:** {c}" for s, c in user_tickets]
                breakdown_str = "\n".join(t_lines) if t_lines else "• No active tickets found."
                
                return {
                    "answer": (
                        f"🎫 **Your Support Tickets: {total_t} total**\n\n"
                        f"Here is the status breakdown of tickets created by or assigned to you:\n\n"
                        f"{breakdown_str}\n\n"
                        f"*Let me know if you would like details on any specific ticket! 😊*"
                    ),
                    "action_buttons": [{"label": "View My Tickets", "path": "/user/tickets"}]
                }

            # 2. Admin System / Warehouse Breakdown
            w_clause_t = " WHERE warehouse_id = :wid " if ctx.warehouse_id else ""
            w_clause_a = " WHERE warehouse_id = :wid " if ctx.warehouse_id else ""
            w_clause_p = " WHERE (warehouse_id = :wid OR warehouse_id IS NULL) " if ctx.warehouse_id else ""
            params = {"wid": ctx.warehouse_id} if ctx.warehouse_id else {}

            is_t = "ticket" in q_lower or "all sub categories" in q_lower
            is_a = "asset" in q_lower or "all sub categories" in q_lower
            is_u = "user" in q_lower or "all sub categories" in q_lower
            if not (is_t or is_a or is_u):
                is_t = is_a = is_u = True

            output_sections = []

            # Ticket Breakdown
            if is_t:
                t_status = ctx.db.execute(text(f"SELECT status, count(*) FROM tickets{w_clause_t} GROUP BY status"), params).fetchall()
                t_prio = ctx.db.execute(text(f"SELECT priority, count(*) FROM tickets{w_clause_t} GROUP BY priority"), params).fetchall()
                t_cat = ctx.db.execute(text(f"SELECT COALESCE(final_category, predicted_category), count(*) FROM tickets{w_clause_t} GROUP BY COALESCE(final_category, predicted_category)"), params).fetchall()
                total_t = sum(c for _, c in t_status)

                status_items = ", ".join([f"{str(s).replace('_', ' ').title()}: {c}" for s, c in t_status if s])
                prio_items = ", ".join([f"{str(p).title()}: {c}" for p, c in t_prio if p])
                cat_items = ", ".join([f"{str(cat).title()}: {c}" for cat, c in t_cat if cat])

                output_sections.append(
                    f"🎫 **Tickets Breakdown (Total: {total_t:,})**\n\n"
                    f"• **By Status:** {status_items or 'None'}\n"
                    f"• **By Priority:** {prio_items or 'None'}\n"
                    f"• **By Category:** {cat_items or 'None'}"
                )

            # Asset Breakdown
            if is_a:
                a_health = ctx.db.execute(text(f"SELECT health_band, count(*) FROM assets{w_clause_a} GROUP BY health_band"), params).fetchall()
                a_status = ctx.db.execute(text(f"SELECT status, count(*) FROM assets{w_clause_a} GROUP BY status"), params).fetchall()
                a_cat = ctx.db.execute(text(f"SELECT category, count(*) FROM assets{w_clause_a} GROUP BY category ORDER BY count(*) DESC LIMIT 6"), params).fetchall()
                total_a = sum(c for _, c in a_status)

                health_items = ", ".join([f"{str(h).title()}: {c}" for h, c in a_health if h])
                status_items = ", ".join([f"{str(s).replace('_', ' ').title()}: {c}" for s, c in a_status if s])
                cat_items = ", ".join([f"{str(cat)}: {c}" for cat, c in a_cat if cat])

                output_sections.append(
                    f"⚙️ **Assets Breakdown (Total: {total_a:,})**\n\n"
                    f"• **By Health Band:** {health_items or 'None'}\n"
                    f"• **By Status:** {status_items or 'None'}\n"
                    f"• **By Vehicle Type / Category:** {cat_items or 'None'}"
                )

            # User Breakdown
            if is_u:
                u_role = ctx.db.execute(text(f"SELECT role, count(*) FROM profiles{w_clause_p} GROUP BY role"), params).fetchall()
                u_status = ctx.db.execute(text(f"SELECT status, count(*) FROM profiles{w_clause_p} GROUP BY status"), params).fetchall()
                total_u = sum(c for _, c in u_role)

                role_items = ", ".join([f"{str(r).replace('_', ' ').title()}: {c}" for r, c in u_role if r])
                status_items = ", ".join([f"{str(s).replace('_', ' ').title()}: {c}" for s, c in u_status if s])

                output_sections.append(
                    f"👥 **Users Breakdown (Total: {total_u:,})**\n\n"
                    f"• **By Role:** {role_items or 'None'}\n"
                    f"• **By Status:** {status_items or 'None'}"
                )

            final_answer = "\n\n".join(output_sections) + "\n\n*Let me know if you need specific details on any category or record! 😊*"
            return {
                "answer": final_answer,
                "action_buttons": [
                    {"label": "View Assets", "path": "/admin/assets"},
                    {"label": "View Tickets", "path": "/admin/tickets"},
                    {"label": "Manage Users", "path": "/admin/users"}
                ]
            }
        except Exception as e:
            log.error("Breakdown fast-path failed: %s", e)

    # ── Step 0: Dashboard/Overview Fast-Path (100% UI Parity) ─────────────────
    general_summary_keywords = ["summary", "overview", "stats", "dashboard stats", "all stats"]
    is_general_summary = any(w in q_lower for w in general_summary_keywords)
    is_details_summary = any(
        f"details about {x}" in q_lower or 
        f"details of {x}" in q_lower or 
        f"{x} details" in q_lower or 
        f"overview of {x}" in q_lower or 
        f"{x} overview" in q_lower or 
        f"{x} stats" in q_lower 
        for x in ["asset", "ticket", "user", "warehouse"]
    )
    is_summary = (is_general_summary or is_details_summary) and not any(w in q_lower for w in ["list", "show all", "get all", "find all"])

    if is_summary:
        if ctx.role not in ["admin", "super_admin"]:
            return {
                "answer": "🔒 You do not have permission to view system-wide statistics. You can only view and manage your own tickets and assigned assets.",
                "action_buttons": [],
            }
        try:
            from app.models import Asset, Ticket, Profile, PdmBatchPrediction
            from sqlalchemy import func, cast, String, case
            
            is_asset = "asset" in q_lower
            is_ticket = "ticket" in q_lower
            is_user = "user" in q_lower or "profile" in q_lower
            
            # 1. Fetch Asset Stats if requested or for overall view
            total_assets, operational, maintenance, critical_band, offline, avg_health_val = 0, 0, 0, 0, 0, 0
            if is_asset or not (is_ticket or is_user):
                asset_q = ctx.db.query(Asset)
                if ctx.warehouse_id:
                    asset_q = asset_q.filter(Asset.warehouse_id == ctx.warehouse_id)
                asset_rows = asset_q.with_entities(
                    func.count(Asset.id),
                    func.count(Asset.id).filter(cast(Asset.status, String) == "active"),
                    func.count(Asset.id).filter(cast(Asset.status, String) == "under_maintenance"),
                    func.count(Asset.id).filter(Asset.health_band == "critical"),
                    func.count(Asset.id).filter(cast(Asset.status, String).in_(("inactive", "decommissioned"))),
                ).one()
                total_assets, operational, maintenance, critical_band, offline = asset_rows
                total_assets = int(total_assets or 0)
                operational = int(operational or 0)
                maintenance = int(maintenance or 0)
                critical_band = int(critical_band or 0)
                offline = int(offline or 0)

                health_q = (
                    ctx.db.query(func.avg(PdmBatchPrediction.health_score))
                    .select_from(Asset)
                    .join(
                        PdmBatchPrediction,
                        (PdmBatchPrediction.asset_id == Asset.id) & (PdmBatchPrediction.status == "ok"),
                    )
                )
                if ctx.warehouse_id:
                    health_q = health_q.filter(Asset.warehouse_id == ctx.warehouse_id)
                avg_health = health_q.scalar()
                avg_health_val = int(round(float(avg_health))) if avg_health is not None else 64

            # 2. Fetch Ticket Stats if requested or for overall view
            open_tickets, high_priority, tickets_resolved, avg_resolution_days = 0, 0, 0, 0.0
            if is_ticket or not (is_asset or is_user):
                ticket_q = ctx.db.query(Ticket)
                if ctx.warehouse_id:
                    ticket_q = ticket_q.filter(Ticket.warehouse_id == ctx.warehouse_id)
                
                ticket_rows = ticket_q.with_entities(
                    func.count(Ticket.id).filter(Ticket.status.notin_(('closed', 'cancelled'))),
                    func.count(Ticket.id).filter((Ticket.priority == 'high') & Ticket.status.notin_(('closed', 'cancelled'))),
                    func.count(Ticket.id).filter(Ticket.status.in_(('resolved', 'closed'))),
                    func.avg(
                        case(
                            [(func.coalesce(Ticket.closed_at, Ticket.resolved_at).isnot(None) & Ticket.created_at.isnot(None),
                             func.extract('epoch', func.coalesce(Ticket.closed_at, Ticket.resolved_at) - Ticket.created_at) / 86400.0)],
                            else_=None
                        )
                    )
                ).one()
                
                open_tickets, high_priority, tickets_resolved, avg_res = ticket_rows
                open_tickets = int(open_tickets or 0)
                high_priority = int(high_priority or 0)
                tickets_resolved = int(tickets_resolved or 0)
                avg_resolution_days = round(float(avg_res), 1) if avg_res is not None else 0.0

            # 3. Fetch User Stats if requested or for overall view
            total_users, active_users, admins, regular_users = 0, 0, 0, 0
            if is_user or not (is_asset or is_ticket):
                users_q = ctx.db.query(Profile)
                if ctx.warehouse_id:
                    users_q = users_q.filter((Profile.warehouse_id == ctx.warehouse_id) | (Profile.warehouse_id.is_(None)))
                all_users = users_q.all()
                total_users = len(all_users)
                active_users = sum(1 for u in all_users if getattr(u, "status", "").lower() == "active")
                admins = sum(1 for u in all_users if getattr(u, "role", "").lower() == "admin")
                regular_users = sum(1 for u in all_users if getattr(u, "role", "").lower() == "user")

            # 4. Construct beautiful Markdown response
            if is_asset:
                answer = (
                    f"⚙️ **Asset Fleet Overview**\n\n"
                    f"Here is a summary of the assets in this warehouse:\n\n"
                    f"• **Total Assets:** {total_assets:,}\n"
                    f"• **Average Health:** {avg_health_val}%\n"
                    f"• **Operational (Active):** {operational:,}\n"
                    f"• **Under Maintenance:** {maintenance:,}\n"
                    f"• **Critical Band:** {critical_band:,}\n"
                    f"• **Offline / Inactive:** {offline:,}"
                )
                action_buttons = [{"label": "View Assets Dashboard", "path": "/admin/assets"}]
            elif is_ticket:
                answer = (
                    f"🎫 **Tickets & Helpdesk Overview**\n\n"
                    f"Here is a summary of the support tickets in this warehouse:\n\n"
                    f"• **Open Tickets:** {open_tickets:,}\n"
                    f"• **High Priority:** {high_priority:,}\n"
                    f"• **Tickets Resolved:** {tickets_resolved:,}\n"
                    f"• **Average Resolution:** {avg_resolution_days} days"
                )
                action_buttons = [{"label": "View Tickets Helpdesk", "path": "/admin/tickets"}]
            elif is_user:
                answer = (
                    f"👥 **User & Team Overview**\n\n"
                    f"Here is a summary of team accounts in this warehouse:\n\n"
                    f"• **Total Users:** {total_users:,}\n"
                    f"• **Active Users:** {active_users:,}\n"
                    f"• **Administrators:** {admins:,}\n"
                    f"• **Standard Users:** {regular_users:,}"
                )
                action_buttons = [{"label": "View User Management", "path": "/admin/users"}]
            else:
                # Overall system-wide overview
                answer = (
                    f"📊 **System-Wide Dashboard Summary**\n\n"
                    f"Here is a summary of current system operations:\n\n"
                    f"• **Total Assets:** {total_assets:,} ({avg_health_val}% Avg. Health)\n"
                    f"• **Active Tickets:** {open_tickets:,} ({high_priority:,} High Priority)\n"
                    f"• **Active Team Members:** {active_users:,} of {total_users:,} total users"
                )
                action_buttons = [{"label": "Go to Dashboard", "path": "/admin/dashboard"}]

            return {
                "answer": answer,
                "action_buttons": action_buttons
            }
        except Exception as e:
            log.error("Overview fast-path failed: %s", e)
            return _get_generic_fallback()
    else:
        goto_summarizer = False

    if not goto_summarizer:
        # ── Step 1: Table Selector (fast model) ──────────────────────────────────
        table_list = ", ".join(DB_SCHEMAS.keys())
        selector_prompt = (
            f"You are a database table selector for PredictiX (Smart Asset Management System).\n"
            f"The user asked: \"{question}\"\n\n"
            f"Available tables: {table_list}\n\n"
            "Respond with ONLY a comma-separated list of up to 4 table names that are needed to answer this question. "
            "No explanations, no other text."
        )
        try:
            raw_tables, fb = call_groq(
                messages=[{"role": "user", "content": selector_prompt}],
                max_tokens=60,
                temperature=0.1,
            )
            if fb and not fallback_msg: fallback_msg = fb
            selected_tables = [t.strip() for t in str(raw_tables).split(",") if t.strip() in DB_SCHEMAS]
        except Exception as e:
            log.error("Table selector failed: %s", e)
            selected_tables = ["tickets", "assets"]

        if not selected_tables:
            selected_tables = ["tickets", "assets"]

        # ── Step 2: SQL Generator (heavy model) ──────────────────────────────────
        schema_str = "\n".join(
            f"Table '{t}': columns → {DB_SCHEMAS[t]}" for t in selected_tables
        )

        # Build role-based scoping instruction
        if ctx.is_admin:
            role_instructions = "SECURITY RULE: The user is an ADMIN. You may query ALL records across the entire system."
            if ctx.warehouse_id:
                role_instructions += f" The admin is scoped to warehouse_id = '{ctx.warehouse_id}'."
        else:
            role_instructions = (
                f"SECURITY RULE: The current user is a STANDARD USER (id='{ctx.user_id}'). "
                "You MUST add a WHERE clause to only show records where created_by = '{user_id}' OR assigned_to = '{user_id}'. "
                "Never expose other users' private data."
            ).replace("{user_id}", ctx.user_id)

        sql_prompt = (
            f"You are a PostgreSQL expert for the PredictiX Smart Asset Management System.\n"
            f"Write a PostgreSQL query to answer the user's question: \"{question}\"\n"
            f"Use ONLY these tables: {selected_tables}\n"
            f"Schema:\n{schema_str}\n"
            f"{role_instructions}\n"
            "CRITICAL QUERY RULES:\n"
            "1. Most critical asset / highest risk asset / lowest health / urgent maintenance:\n"
            "   - If querying critical or failing assets, query `assets` joined with `pdm_batch_predictions` on `assets.id = pdm_batch_predictions.asset_id`\n"
            "   - Select columns: `assets.id, assets.asset_name, assets.asset_code, assets.category, assets.vehicle_type, assets.status, assets.health_band, pdm_batch_predictions.failure_probability, pdm_batch_predictions.health_score, pdm_batch_predictions.risk_level, pdm_batch_predictions.predicted_maintenance_date`\n"
            "   - Order by: `pdm_batch_predictions.failure_probability DESC, pdm_batch_predictions.health_score ASC` or `assets.criticality_score DESC` LIMIT 1\n"
            "2. Count / Breakdown / Category queries:\n"
            "   - For ticket counts/breakdowns: `SELECT status, count(*) as count FROM tickets GROUP BY status;` or `SELECT priority, count(*) as count FROM tickets GROUP BY priority;` or `SELECT final_category, count(*) as count FROM tickets GROUP BY final_category;`\n"
            "   - For asset counts/breakdowns: `SELECT category, count(*) as count FROM assets GROUP BY category;` or `SELECT health_band, count(*) as count FROM assets GROUP BY health_band;` or `SELECT status, count(*) as count FROM assets GROUP BY status;`\n"
            "   - For user counts/breakdowns: `SELECT role, count(*) as count FROM profiles GROUP BY role;` or `SELECT status, count(*) as count FROM profiles GROUP BY status;`\n"
            "3. Single record lookup: Always return `SELECT *` or all essential fields including `id` so the system can render a rich record card.\n"
            "4. Respond ONLY with raw valid PostgreSQL SQL. No markdown, no backticks, no explanations.\n"
            "5. If the question cannot be answered using the schema, output EXACTLY: 'ERROR: reason'"
        )

        try:
            raw_sql, fb = call_groq(
                messages=[{"role": "user", "content": sql_prompt}],
                model="llama-3.3-70b-versatile",
                max_tokens=350,
                temperature=0.1,
            )
            if fb and not fallback_msg: fallback_msg = fb
            sql = str(raw_sql).strip().lstrip("```sql").lstrip("```").rstrip("```").strip()
        except Exception as e:
            log.error("SQL generator failed: %s", e)
            return _get_contextual_fallback("SQL generator failed")

        if sql.startswith("ERROR: Permission Denied"):
            return {
                "answer": "🔒 You do not have permission to view system-wide data. You can only view records assigned to or created by you.",
                "action_buttons": [],
            }

        if sql.startswith("ERROR: Permission Denied"):
            return {
                "answer": "🔒 You do not have permission to view system-wide data. You can only view records assigned to or created by you.",
                "action_buttons": [],
            }

        if sql.startswith("ERROR:"):
            return _get_contextual_fallback(sql)

        # Security guard: block any mutation
        import re
        sql_upper = sql.upper()
        for dangerous in ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "TRUNCATE", "GRANT"]:
            if re.search(rf"\b{dangerous}\b", sql_upper):
                return _get_generic_fallback()

        # ── Step 3: Execute (with self-healing retry on DB error) ────────────────
        if ctx.db is None:
            return {"answer": "⚠️ Database is not available right now. Please try again in a moment.", "action_buttons": []}

        def _run_sql(sql_to_run: str):
            result = ctx.db.execute(text(sql_to_run)).fetchall()
            if not result:
                return None
            keys = list(result[0]._mapping.keys())
            return [dict(zip(keys, row)) for row in result[:50]]

        rows = None
        try:
            rows = _run_sql(sql)
        except Exception as first_err:
            log.warning("SQL execution failed (attempt 1): %s | SQL: %s", first_err, sql)
            ctx.db.rollback()
            # Self-healing: feed the error back to the LLM to fix the SQL
            try:
                fix_prompt = (
                    f"The following PostgreSQL query failed with this error:\n"
                    f"ERROR: {str(first_err)[:300]}\n\n"
                    f"FAILED SQL:\n{sql}\n\n"
                    f"SCHEMA (correct ENUM values):\n{schema_str}\n\n"
                    "Fix the SQL query. Common fixes:\n"
                    "- assets.status valid values: active, inactive, maintenance, retired, disposed (NOT 'open')\n"
                    "- tickets.status valid values: open, in_progress, pending, resolved, closed, cancelled\n"
                    "- Use CAST if comparing text with enum column\n"
                    "Output ONLY the corrected raw SQL. No markdown, no backticks."
                )
                corrected_sql_raw, _ = call_groq(
                    messages=[{"role": "user", "content": fix_prompt}],
                    model="llama-3.3-70b-versatile",
                    max_tokens=350,
                    temperature=0.1,
                )
                corrected_sql = str(corrected_sql_raw).strip().lstrip("```sql").lstrip("```").rstrip("```").strip()
                log.info("Self-healed SQL: %s", corrected_sql)
                rows = _run_sql(corrected_sql)
                sql = corrected_sql  # update for logging
            except Exception as second_err:
                log.error("SQL self-healing also failed: %s", second_err)
                ctx.db.rollback()
                return _get_contextual_fallback(str(second_err))

        if rows is None:
            return {"answer": "📊 The query ran successfully but returned no results. The data matching your request may not exist yet.", "action_buttons": []}

    # ── Fast-Path for Single Records (Widget) ──────────────────────────────
    # If the database returns exactly 1 record AND it has an ID, we bypass the
    # text summarizer and return a rich widget.
    if rows and len(rows) == 1 and "id" in rows[0] and not goto_summarizer:
        row = rows[0]
        row_id = str(row["id"])
        
        # Determine table/type
        table_type = "unknown"
        if "tickets" in selected_tables: table_type = "ticket"
        elif "assets" in selected_tables: table_type = "asset"
        elif "profiles" in selected_tables or "users" in selected_tables: table_type = "user"
        
        if table_type != "unknown":
            action_buttons = []
            if table_type == "ticket":
                base_path = "/admin/tickets" if ctx.is_admin else "/user/tickets"
                action_buttons.append({"label": "View Ticket", "path": f"{base_path}?ticket_id={row_id}"})
            elif table_type == "asset":
                action_buttons.append({"label": "View Asset", "path": f"/admin/assets?asset_id={row_id}"})
            elif table_type == "user":
                action_buttons.append({"label": "View User", "path": f"/admin/users?user_id={row_id}"})
                
            # Convert row to dict, ensuring datetime objects are strings
            def _serialize(v):
                if hasattr(v, "isoformat"): return v.isoformat()
                return str(v) if v is not None else None
            
            clean_data = {str(k): _serialize(v) for k, v in row.items()}
            
            return {
                "answer": f"Here is the detailed summary card you requested:",
                "action_buttons": action_buttons,
                "widget_type": "RECORD_SUMMARY",
                "widget_data": {
                    "type": table_type,
                    "data": clean_data
                }
            }

    # ── Step 4: Summarize (fast model) ───────────────────────────────────────
    row_str = str(rows[:30])  # cap context to keep tokens low

    # Build a direct plain-text fallback from the raw rows (used if LLM fails)
    def _build_fallback(rows: list[dict]) -> str:
        if not rows:
            return "📊 No data found."
        lines = [f"📊 **Results ({len(rows)} record{'s' if len(rows) != 1 else ''}):**\n"]
        for i, row in enumerate(rows):
            keys = list(row.keys())
            # Clean format for two-column stats (e.g. Metric/Count, Category/Total)
            if len(keys) == 2 and str(keys[1]).lower() in ["count", "value", "total", "amount", "sum"]:
                lines.append(f"• **{row[keys[0]]}:** {row[keys[1]]}")
            else:
                lines.append(f"\n### 📝 Record #{i+1}")
                for k, v in row.items():
                    if v is not None and str(v).strip():
                        # Exclude displaying raw system IDs in the fallback list to keep it clean
                        if k == "id" or k.endswith("_id"):
                            continue
                        pretty_key = str(k).replace("_", " ").title()
                        lines.append(f"  - **{pretty_key}:** {v}")
        return "\n".join(lines)

    summarizer_prompt = (
        f"You are Sidekick, the PredictiX AI Assistant. A user asked: \"{question}\"\n"
        f"The database returned this data: {row_str}\n\n"
        "FORMATTING & RESPONSE INSTRUCTIONS:\n"
        "1. Specific/Critical Asset Lookups (e.g. most critical asset, highest risk asset):\n"
        "   - Give a clear, highlighted title with the Asset Name & Code (e.g. ⚙️ **Most Critical Asset: Delivery Van (1.5T) [LL-VAN-001]**).\n"
        "   - List all important health indicators: Health Score (%), Failure Probability (%), Health Band/Status, Risk Level, and Predicted Maintenance Date in bullet points.\n"
        "2. Count & Breakdown Queries (e.g. number of tickets, users, assets by sub-category):\n"
        "   - Start with a clear ONE-LINE summary of the TOTAL count (e.g. 🎫 **Total Support Tickets: 935**).\n"
        "   - Present the breakdown with clean bullet points, bold category names, and exact counts (e.g. • **Open:** 83 tickets).\n"
        "3. Use professional emojis (🎫 for tickets, ⚙️ for assets, 👥 for users, 📊 for stats, ⚠️ for critical/high risk).\n"
        "4. Quote EXACT numbers from the data — never invent, round, or approximate numbers.\n"
        "5. Never expose raw UUIDs unless the user provided one.\n"
        "6. End with a polite closing sentence (e.g. '*Let me know if you would like more details on any specific record! 😊*')."
    )
    try:
        summary, fb = call_groq(
            messages=[{"role": "user", "content": summarizer_prompt}],
            max_tokens=400,
            temperature=0.2,
        )
        if fb and not fallback_msg: fallback_msg = fb
        if not summary or len(str(summary).strip()) < 10:
            summary = _build_fallback(rows)
    except Exception as e:
        log.error("Summarizer failed: %s", e)
        summary = _build_fallback(rows)

    # Determine interactive action buttons based on queried tables
    action_buttons = []
    
    # Fast-path for single records: provide a deep-link button directly to the item!
    if rows and len(rows) == 1 and "id" in rows[0]:
        row_id = str(rows[0]["id"])
        if "tickets" in selected_tables:
            base_path = "/admin/tickets" if ctx.is_admin else "/user/tickets"
            action_buttons.append({"label": "View Ticket", "path": f"{base_path}?ticket_id={row_id}"})
        elif "assets" in selected_tables:
            action_buttons.append({"label": "View Asset", "path": f"/admin/assets?asset_id={row_id}"})
        elif "profiles" in selected_tables or "users" in selected_tables:
            action_buttons.append({"label": "View User", "path": f"/admin/users?user_id={row_id}"})
    else:
        if "profiles" in selected_tables or "users" in selected_tables:
            action_buttons.append({"label": "Manage Users", "path": "/admin/users"})
        if "tickets" in selected_tables:
            base_path = "/admin/tickets" if ctx.is_admin else "/user/tickets"
            action_buttons.append({"label": "View Tickets", "path": base_path})
        if "assets" in selected_tables:
            action_buttons.append({"label": "View Assets", "path": "/admin/assets"})
        if "warehouses" in selected_tables:
            action_buttons.append({"label": "View Warehouses", "path": "/admin/warehouse"})

    # Limit to 2 buttons max so it doesn't clutter the UI
    action_buttons = action_buttons[:2]

    return {
        "answer": fallback_msg + str(summary),
        "action_buttons": action_buttons,
    }



def handle_prediction_info(question: str, ctx: ToolContext) -> dict:
    """Handles questions about how to USE prediction models + shows predictions data."""
    q_lower = question.lower()

    # If the user wants to KNOW HOW to use the models → give guidance + button
    how_to_keywords = ["how", "how to", "use", "run", "generate", "where", "start", "launch"]
    is_how_to = any(kw in q_lower for kw in how_to_keywords)

    if is_how_to and "predict" in q_lower or "report" in q_lower or "cost estimat" in q_lower:
        answer = (
            "🤖 **AI Prediction Models in PredictiX:**\n\n"
            "**🔮 Failure Prediction (Predictive Maintenance)**\n"
            "• Go to any Asset → Click **Run Prediction** → The AI calculates failure probability, health score, and predicted maintenance date.\n\n"
            "**💰 Cost Estimation**\n"
            "• Go to **Reports** → Select **Cost Prediction** → Choose an asset or warehouse to estimate maintenance costs.\n\n"
            "**🎫 Ticket AI Classification**\n"
            "• When creating or viewing a ticket, the AI automatically predicts its category and priority.\n\n"
            "**📦 Batch Predictions (PDM)**\n"
            "• Go to **Reports** → Select **Batch PDM** to run predictions for all assets at once.\n\n"
            "Please visit the Helpdesk section for more details. Contact admin at neuromindspredictix@gmail.com."
        )
        buttons = [
            {"label": "Go to Reports / Predictions", "path": "/admin/reports"},
            {"label": "Go to Assets", "path": "/admin/assets"},
        ]
        return {"answer": answer, "action_buttons": buttons}
    # Otherwise, check if they are asking about a specific asset's health/prediction for the widget demo
    if "show asset health card" in q_lower or "health card for" in q_lower:
        # For the proof-of-concept Widget, we return a mock/real asset data payload
        return {
            "answer": "Here is the latest predictive health assessment for the requested asset.",
            "action_buttons": [],
            "widget_type": "ASSET_HEALTH",
            "widget_data": {
                "name": "Heavy Duty Forklift A-1",
                "healthScore": 82,
                "status": "Warning",
                "failureProbability": 0.45,
                "predictedFailureDate": "2026-08-15"
            }
        }

    # Otherwise, query the actual prediction data from DB
    return handle_database(question, ctx)
