<<<<<<< HEAD
"""Tool definitions for the PredictiX chatbot agent (v2: agentic db access)."""
=======
"""PredictiX Chatbot – Pure-Python Tool Handlers & Zero-Token Handlers.

Architecture:
  - Zero-Token handlers: Greeting, Navigation, WhoAmI, FAQ
    → No LLM call at all. Instant, deterministic responses.
  - Database handler: executes SQL generated by a sub-agent
  - Knowledge handler: semantic search on the knowledge base
  - Prediction handler: queries all ML prediction tables
"""
>>>>>>> 35e3ac103591052fc88dd59200e314bb3792f95b
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Optional

from sqlalchemy import text
from sqlalchemy.orm import Session
from sqlalchemy import text
from pydantic import BaseModel

from app.db.supabase_client import supabase

log = logging.getLogger("predictix.tools")

<<<<<<< HEAD
=======

# ─── Context ─────────────────────────────────────────────────────────────────

>>>>>>> 35e3ac103591052fc88dd59200e314bb3792f95b
@dataclass
class ToolContext:
    """Per-request context handed to every handler."""
    db: Optional[Session]
    user: Any  # Profile or MockProfile

    @property
    def is_admin(self) -> bool:
        return str(getattr(self.user, "role", "")).lower() in ("admin", "super_admin")

    @property
    def user_id(self) -> str:
        return str(getattr(self.user, "id", ""))

<<<<<<< HEAD
def _require_db(ctx: ToolContext) -> Session:
    if ctx.db is None:
        raise RuntimeError("Database is not configured for this request.")
    return ctx.db

# ─── Schema definitions for the sub-agent ─────────────────────────────────────
DB_SCHEMAS = {
=======
    @property
    def role(self) -> str:
        return str(getattr(self.user, "role", "user")).lower()

    @property
    def full_name(self) -> str:
        return str(getattr(self.user, "full_name", "Unknown User"))

    @property
    def warehouse_id(self) -> Optional[str]:
        wid = getattr(self.user, "warehouse_id", None)
        return str(wid) if wid else None


# ─── Full Database Schema ─────────────────────────────────────────────────────

DB_SCHEMAS: dict[str, str] = {
>>>>>>> 35e3ac103591052fc88dd59200e314bb3792f95b
    "warehouses": "id, code, name, address, city, district, country, timezone, is_active, climate_zone, warehouse_type, metadata, created_at, updated_at",
    "departments": "id, warehouse_id, code, name, description, is_active, created_at, updated_at",
    "profiles": "id, employee_id, full_name, email, phone, role, status, warehouse_id, department_id, avatar_url, meta, created_at, updated_at",
    "assets": "id, asset_code, warehouse_id, department_id, asset_name, asset_type, category, vehicle_type, make, model, manufacture_year, registration_number, vin, status, health_band, criticality_score, purchase_date, warranty_expiry_date, assigned_to, current_mileage, last_service_date, next_service_date, description, fuel_type, transmission, make_model, maintenance_priority, service_provider_type, metadata, created_by, vehicle_role, payload_capacity_kg, vehicle_age_years, lifetime_service_count, lifetime_breakdown_count, created_at, updated_at",
    "maintenance_events": "id, asset_id, event_type, title, description, performed_by, scheduled_date, performed_at, odometer_reading, downtime_hours, cost_amount, currency, vendor_name, notes, metadata, created_at, updated_at",
<<<<<<< HEAD
    "sensor_readings": "id, asset_id, recorded_at, temperature, vibration, pressure, humidity, rpm, voltage, fuel_level, odometer, engine_hours_since_last_service, days_since_last_service, tire_health_pct, brake_health_pct, mileage_since_last_service_km, battery_health_pct, oil_life_pct, hydraulic_health_pct, vibration_rms_mm_s, fuel_price_lkr_per_l, engine_hours_total, coolant_temp_max_c, engine_temp_avg_c, battery_voltage_v, odometer_km, downtime_hours_last_90d, active_fault_code_count, distance_last_30d_km, payload_utilization_pct, trip_count_30d, ambient_humidity_avg_pct, rough_road_pct, idle_hours_last_30d, port_route_pct, overload_events_30d, fuel_rate_lph, avg_payload_kg, ambient_temp_avg_c, avg_trip_distance_km, cargo_type, fuel_efficiency_km_per_l, is_home_warehouse_service, last_service_type, maintenance_cost_last_service_lkr, major_component_replaced, operating_hours_last_30d, operating_shift, parts_replaced_last_service, rainfall_mm_30d, route_type, sensor_fault_flag, start_stop_burden_30d, tire_pressure_psi, urban_route_pct, reading_payload",
    "tickets": "id, ticket_number, asset_id, warehouse_id, title, description, status(open, in_progress, pending, resolved, closed, cancelled), priority(low, medium, high), predicted_priority, final_priority, predicted_category(electrical, mechanical, software), final_category, ticket_summary, asset_summary, created_by, assigned_to, reviewed_by, opened_at, reviewed_at, resolved_at, closed_at, metadata, created_at, updated_at",
    "prediction_runs": "id, model_id, asset_id, ticket_id, input_snapshot, requested_by, run_started_at, run_finished_at, status, error_message",
    "reports": "id, report_type, status, asset_id, warehouse_id, ticket_id, title, generated_by, report_text, report_json, file_path, generation_started_at, generation_completed_at, created_at, updated_at",
    "notifications": "id, user_id, type, channel, title, message, status, related_asset_id, related_ticket_id, related_report_id, sent_at, read_at, metadata, created_at",
    "asset_assignments": "id, asset_id, user_id, assigned_by, assigned_at, unassigned_at, is_active, notes",
    "asset_status_history": "id, asset_id, old_status, new_status, changed_by, reason, created_at",
    "asset_documents": "id, asset_id, title, file_path, mime_type, document_type, uploaded_by, metadata, created_at",
    "ticket_comments": "id, ticket_id, user_id, comment, is_internal, created_at",
    "ticket_attachments": "id, ticket_id, file_path, mime_type, original_filename, uploaded_by, created_at",
    "ticket_status_history": "id, ticket_id, old_status, new_status, changed_by, note, created_at",
    "model_registry": "id, model_name, model_type, version, framework, artifact_path, metrics, is_active, created_at",
=======
    "sensor_readings": "id, asset_id, recorded_at, temperature, vibration, pressure, humidity, rpm, voltage, fuel_level, odometer, engine_hours_since_last_service, days_since_last_service, tire_health_pct, brake_health_pct, battery_health_pct, oil_life_pct, hydraulic_health_pct, vibration_rms_mm_s, fuel_efficiency_km_per_l, engine_hours_total, coolant_temp_max_c, battery_voltage_v, odometer_km",
    "tickets": "id, ticket_number, asset_id, warehouse_id, title, description, status(open/in_progress/pending/resolved/closed/cancelled), priority(low/medium/high), predicted_priority, final_priority, predicted_category(electrical/mechanical/software), final_category, ticket_summary, created_by, assigned_to, reviewed_by, opened_at, reviewed_at, resolved_at, closed_at, created_at, updated_at",
    "prediction_runs": "id, model_id, asset_id, ticket_id, input_snapshot, requested_by, run_started_at, run_finished_at, status, error_message",
    "reports": "id, report_type, status, asset_id, warehouse_id, ticket_id, title, generated_by, report_text, report_json, file_path, generation_started_at, generation_completed_at, created_at",
    "notifications": "id, user_id, type, channel, title, message, status, related_asset_id, related_ticket_id, sent_at, read_at, created_at",
    "asset_assignments": "id, asset_id, user_id, assigned_by, assigned_at, unassigned_at, is_active, notes",
    "asset_status_history": "id, asset_id, old_status, new_status, changed_by, reason, created_at",
    "ticket_comments": "id, ticket_id, user_id, comment, is_internal, created_at",
    "ticket_status_history": "id, ticket_id, old_status, new_status, changed_by, note, created_at",
    "model_registry": "id, model_name, model_type, version, framework, artifact_path, metrics, is_active, created_at",
    # ML Prediction tables
>>>>>>> 35e3ac103591052fc88dd59200e314bb3792f95b
    "asset_failure_predictions": "id, run_id, asset_id, health_score, failure_probability, confidence, risk_level, predicted_maintenance_date, days_until_maintenance, top_explanations, created_at",
    "asset_cost_predictions": "id, run_id, asset_id, estimated_cost, min_cost, max_cost, currency, confidence_score, created_at",
    "ticket_predictions": "id, run_id, ticket_id, predicted_category, predicted_priority, category_confidence, priority_confidence, generated_summary, created_at",
    "prediction_explanations": "id, run_id, asset_id, explanation_type, explanation_text, created_at",
    "prediction_feature_importance": "id, explanation_id, feature_name, feature_value, importance_score, direction, rank_order",
<<<<<<< HEAD
    "report_sources": "id, report_id, source_table, source_id, source_label, relevance_score, created_at",
    "user_notification_preferences": "id, user_id, channel, notification_type, enabled, created_at, updated_at",
    "pdm_batch_predictions": "id, asset_id, failure_probability, maintenance_required, risk_level, predicted_days_until_maintenance, predicted_maintenance_date, health_score, health_status, contributing_factors, estimated_cost_lkr, min_cost_lkr, max_cost_lkr, top_explanations, predicted_at, run_duration_ms, error_message, status",
}

def _tool_supabase_access(args: dict, ctx: ToolContext) -> dict:
    """Uses the database sub-agent to execute a safe read-only SQL query."""
    from app.ai.agent.agent_service import get_sql_from_subagent
    
    tables = args.get("tables", [])
    instruction = args.get("instruction", "")
    if not tables or not instruction:
        return {"error": "tables and instruction are required."}

    # Gather schema only for the requested tables
    schema_details = []
    for t in tables:
        if t in DB_SCHEMAS:
            schema_details.append(f"Table '{t}': {DB_SCHEMAS[t]}")
        else:
            schema_details.append(f"Table '{t}': Unknown table")
    
    schema_str = "\\n".join(schema_details)
    
    # 1. Ask the sub-agent to write the SQL query
    sql_query = get_sql_from_subagent(instruction, schema_str)
    
    if "ERROR:" in sql_query:
        return {"error": sql_query}
        
    # Security: Ensure it's read-only
    if any(kw in sql_query.upper() for kw in ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "TRUNCATE"]):
        return {"error": "Only SELECT queries are allowed."}

    # 2. Execute the query
    db = _require_db(ctx)
    try:
        # Enforce scope if non-admin
        # We'll rely on the sub-agent being told about the current_user_id
        result = db.execute(text(sql_query)).fetchall()
        
        # Convert rows to dict
        keys = result[0]._mapping.keys() if result else []
        rows = [dict(zip(keys, row)) for row in result]
        return {"sql_executed": sql_query, "results": rows[:50]} # Cap at 50 rows
    except Exception as e:
        return {"error": f"SQL execution failed: {e}", "sql_attempted": sql_query}


def _tool_list_faqs(args: dict, ctx: ToolContext) -> dict:
    search = (args.get("search") or "").strip().lower()
    response = (
        supabase.from_("faqs")
        .select("id,question,answer,category")
        .eq("is_active", True)
        .order("created_at", desc=True)
        .execute()
    )
    rows = response.data or []
    if search:
        rows = [r for r in rows if search in r["question"].lower() or search in r["answer"].lower()]
    rows = rows[: int(args.get("limit", 5))]
    return {"count": len(rows), "faqs": rows}


def _tool_search_knowledge(args: dict, ctx: ToolContext) -> dict:
    from app.ai.services.knowledge_service import search_knowledge
    query = args.get("query", "").strip()
    if not query:
        return {"error": "query is required"}
    results = search_knowledge(query, match_count=int(args.get("match_count", 3)))
    return {"count": len(results), "results": results}


def _tool_whoami(args: dict, ctx: ToolContext) -> dict:
    """Return basic info about the current user."""
    return {
        "id": ctx.user_id,
        "email": getattr(ctx.user, "email", None),
        "role": getattr(ctx.user, "role", "user"),
        "full_name": getattr(ctx.user, "full_name", None),
        "department_id": str(ctx.user.department_id) if getattr(ctx.user, "department_id", None) else None,
        "warehouse_id": str(ctx.user.warehouse_id) if getattr(ctx.user, "warehouse_id", None) else None,
    }


def _tool_mr_guideline_helper(args: dict, ctx: ToolContext) -> dict:
    """Return system navigation guidelines for Mr. Guideline Helper."""
    question = args.get("question", "").lower()
    
    # Generic helpdesk/navigation instructions
    guidelines = "Mr. Guideline Helper says:\\n"
    if "password" in question:
        guidelines += "To change your password, click on your profile avatar in the top right corner, go to 'Profile Settings', and select 'Change Password'.\\n"
    elif "helpdesk" in question or "ticket" in question:
        guidelines += "To access the Helpdesk and manage tickets, click on 'Helpdesk' in the main navigation sidebar.\\n"
    elif "asset" in question:
        guidelines += "To view or manage assets, click on 'Assets' in the main navigation sidebar.\\n"
    elif "report" in question:
        guidelines += "To generate reports, click on 'Reports' in the main navigation sidebar.\\n"
    else:
        guidelines += "You can navigate the system using the sidebar on the left. You'll find sections for Dashboard, Assets, Helpdesk, Reports, and Settings.\\n"
        
    guidelines += "\\nPlease visit the Helpdesk section for more details. If you need further support, contact the admin at neuromindspredictix@gmail.com."
    
    return {"guideline": guidelines}


# ─── Tool registry ────────────────────────────────────────────────────────────

TOOL_HANDLERS: dict[str, Callable[[dict, ToolContext], Any]] = {
    "whoami": _tool_whoami,
    "supabase_access": _tool_supabase_access,
    "list_faqs": _tool_list_faqs,
    "search_knowledge": _tool_search_knowledge,
    "mr_guideline_helper": _tool_mr_guideline_helper,
}

TOOL_SCHEMAS: list[dict] = [
    {
        "type": "function",
        "function": {
            "name": "whoami",
            "description": "Return information about the currently logged-in user (id, email, role, department). Call this first when you need to know who you're helping.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "supabase_access",
            "description": "Execute a database query against Supabase to get real data. Use this for ANY question about tickets, assets, users, or any other DB entity.",
            "parameters": {
                "type": "object",
                "properties": {
                    "tables": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of table names you need to answer the question (e.g. ['tickets', 'profiles'])",
                    },
                    "instruction": {
                        "type": "string",
                        "description": "What data you need. Include any filters (e.g. 'Count users grouped by role', or 'List 5 most recent tickets for user_id X')",
                    },
                },
                "required": ["tables", "instruction"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "list_faqs",
            "description": "Browse the FAQ knowledge base. Use this first for general 'how do I...' questions.",
            "parameters": {
                "type": "object",
                "properties": {
                    "search": {"type": "string", "description": "Optional keyword to filter FAQs."},
                    "limit": {"type": "integer", "default": 5, "maximum": 20},
                },
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "search_knowledge",
            "description": "Semantic vector search over the knowledge base. Use for fuzzy/conceptual questions.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "The natural-language search query."},
                    "match_count": {"type": "integer", "default": 3, "maximum": 10},
                },
                "required": ["query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "mr_guideline_helper",
            "description": "An agent/tool to help users navigate the system, such as how to go to the helpdesk, how to change a password, or any other system related question.",
            "parameters": {
                "type": "object",
                "properties": {
                    "question": {"type": "string", "description": "The user's question about how to navigate or use the system."},
                },
                "required": ["question"],
            },
        },
    },
=======
    "pdm_batch_predictions": "id, asset_id, failure_probability, maintenance_required, risk_level, predicted_days_until_maintenance, predicted_maintenance_date, health_score, health_status, contributing_factors, estimated_cost_lkr, min_cost_lkr, max_cost_lkr, top_explanations, predicted_at, run_duration_ms, status",
    "report_sources": "id, report_id, source_table, source_id, source_label, relevance_score, created_at",
}

# ─── Navigation Map ────────────────────────────────────────────────────────────

# Maps keywords to (instructions, route, button_label)
NAV_MAP: list[tuple[list[str], str, str, str]] = [
    (["password", "change password"], "To change your password:\n1️⃣ Click your avatar in the top-right corner.\n2️⃣ Select **Profile Settings**.\n3️⃣ Click **Change Password** and follow the prompts.", "/user/profile", "Go to Profile Settings"),
    (["profile", "settings", "account"], "To view or edit your profile:\n1️⃣ Click your avatar in the top-right corner.\n2️⃣ Select **Profile Settings**.", "/user/profile", "Open Profile Settings"),
    (["dashboard", "home", "overview"], "The Dashboard is your main landing page after login. It shows live stats for assets, tickets, and fleet health.", "/admin/dashboard", "Go to Dashboard"),
    (["helpdesk", "help desk", "ticket", "raise ticket", "create ticket", "new ticket"], "To create or manage support tickets:\n1️⃣ Click **Helpdesk** in the left sidebar.\n2️⃣ Click **New Ticket** to raise one.", "/admin/help-desk", "Go to Helpdesk"),
    (["asset", "assets", "fleet", "vehicle"], "To view and manage assets:\n1️⃣ Click **Assets** in the left sidebar.\n2️⃣ Use filters to search by status, type, or warehouse.", "/admin/assets", "Go to Assets"),
    (["report", "reports", "generate report"], "To generate reports:\n1️⃣ Click **Reports** in the left sidebar.\n2️⃣ Select the report type (Asset, Ticket, Prediction).\n3️⃣ Click **Generate**.", "/admin/reports", "Go to Reports"),
    (["warehouse", "warehouses", "location"], "To view warehouses:\n1️⃣ Click **Warehouse** in the left sidebar.", "/admin/warehouses", "Go to Warehouses"),
    (["user", "users", "team", "staff", "manage users"], "To manage users:\n1️⃣ Click **Users** in the left sidebar.\n2️⃣ You can add, edit, or deactivate users here.", "/admin/users", "Go to Users"),
    (["prediction", "predict", "failure prediction", "maintenance prediction", "predictive maintenance"], "To run AI predictions:\n1️⃣ Go to the **Assets** section.\n2️⃣ Open an asset and click **Run Prediction**.\nOr visit the **Reports** section to view all batch predictions.", "/admin/reports", "Go to Predictions / Reports"),
    (["cost", "cost estimation", "cost prediction", "maintenance cost"], "To view cost predictions:\n1️⃣ Go to the **Assets** section.\n2️⃣ Open any asset and view the **Cost Estimation** panel.\nOr visit **Reports** for batch cost reports.", "/admin/reports", "Go to Cost Reports"),
    (["notification", "notifications", "alerts"], "To view your notifications, click the 🔔 bell icon in the top navigation bar.", "/admin/notifications", "Go to Notifications"),
>>>>>>> 35e3ac103591052fc88dd59200e314bb3792f95b
]


# ─── Zero-Token Handlers ──────────────────────────────────────────────────────

def handle_greeting(ctx: ToolContext) -> dict:
    """Returns instant greeting without any LLM call."""
    name = ctx.full_name.split()[0] if ctx.full_name else "there"
    menu = (
        f"👋 Hello, **{name}**! I'm **PredictiX Assistant**. Here's what I can help you with:\n\n"
        "📊 **Data & Analytics** — Ask about tickets, assets, users, warehouses\n"
        "🤖 **AI Predictions** — Failure probabilities, maintenance dates, cost estimations\n"
        "🧭 **Navigation** — *\"How do I change my password?\"*, *\"Where are reports?\"*\n"
        "❓ **FAQs** — Browse frequently asked questions\n"
        "📚 **Knowledge Base** — Policies, procedures, documentation\n"
        "👤 **Your Profile** — *\"Who am I?\"*, *\"What is my role?\"*\n\n"
        "Type **menu** anytime to see this again, or just ask your question!"
    )
    return {"answer": menu, "action_buttons": []}


def handle_whoami(ctx: ToolContext) -> dict:
    """Returns user profile without any LLM call."""
    user = ctx.user
    role = getattr(user, "role", "user")
    full_name = getattr(user, "full_name", "Unknown")
    email = getattr(user, "email", "N/A")
    employee_id = getattr(user, "employee_id", "N/A")
    status = getattr(user, "status", "active")
    wid = getattr(user, "warehouse_id", None)
    did = getattr(user, "department_id", None)

    lines = [
        f"👤 **Your Profile**\n",
        f"• **Name:** {full_name}",
        f"• **Email:** {email}",
        f"• **Role:** {role.replace('_', ' ').title()}",
        f"• **Employee ID:** {employee_id}",
        f"• **Status:** {'✅ Active' if status == 'active' else '❌ ' + status.title()}",
    ]
    if wid:
        lines.append(f"• **Warehouse ID:** {wid}")
    if did:
        lines.append(f"• **Department ID:** {did}")

    return {
        "answer": "\n".join(lines),
        "action_buttons": [{"label": "Go to My Profile", "path": "/user/profile"}],
    }


def handle_navigation(question: str, ctx: ToolContext) -> dict:
    """Returns navigation guidance and a clickable action button. 0 tokens."""
    q_lower = question.lower()
    for keywords, instruction, route, button_label in NAV_MAP:
        if any(kw in q_lower for kw in keywords):
            return {
                "answer": f"🧭 {instruction}\n\nPlease visit the Helpdesk section for more details. If you need further support, contact the admin at neuromindspredictix@gmail.com.",
                "action_buttons": [{"label": button_label, "path": route}],
            }
    # Generic fallback
    return {
        "answer": "🧭 You can navigate the system using the left sidebar:\n• **Dashboard** — Overview & live stats\n• **Assets** — Fleet management\n• **Helpdesk** — Tickets & support\n• **Reports** — AI predictions & analytics\n• **Users** — Team management\n• **Warehouses** — Location management",
        "action_buttons": [{"label": "Go to Dashboard", "path": "/admin/dashboard"}],
    }


def handle_faq(question: str, ctx: ToolContext) -> dict:
    """Fetch FAQs from Supabase, synthesize with LLM, and fallback to admin if not found."""
    from app.ai.services.llm_service import call_groq

    def _get_faq_fallback() -> dict:
        return {
            "answer": "Please reach out to our admins at **neuromindspredictix@gmail.com** and they'll get back to you as soon as possible.",
            "action_buttons": [{"label": "Copy Admin Email", "path": "copy:neuromindspredictix@gmail.com"}],
        }

    try:
<<<<<<< HEAD
        # Add user context to supabase_access args so sub-agent can scope queries
        if name == "supabase_access":
            args["instruction"] = f"{args.get('instruction', '')}. IMPORTANT: Current user_id is '{ctx.user_id}' and role is '{getattr(ctx.user, 'role', 'user')}'. If role is not admin, you MUST scope any queries (like tickets or assets) to only show records where assigned_to or created_by equals this user_id."
        return handler(args or {}, ctx)
=======
        resp = (
            supabase.from_("faqs")
            .select("id,question,answer,category")
            .eq("is_active", True)
            .execute()
        )
        all_faqs = resp.data or []
>>>>>>> 35e3ac103591052fc88dd59200e314bb3792f95b
    except Exception as e:
        log.warning("FAQ fetch failed: %s", e)
        all_faqs = []

    q_lower = question.lower()
    words = [w for w in q_lower.split() if len(w) > 2]
    scored = []
    for faq in all_faqs:
        faq_q = faq.get("question", "").lower()
        faq_a = faq.get("answer", "").lower()
        score = sum(2 for w in words if w in faq_q) + sum(1 for w in words if w in faq_a)
        if score > 0:
            scored.append((score, faq))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = [faq for _, faq in scored[:4]]

    if not top:
        return _get_faq_fallback()

    context_str = "\n".join(
        f"Q: {faq['question']}\nA: {faq['answer']}" for faq in top
    )
    user_name = ctx.full_name.split()[0] if ctx.full_name else "there"

    try:
        summary, fb = call_groq(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are PredictiX Assistant. Answer the user's question using ONLY the provided FAQ context. "
                        "CRITICAL INSTRUCTION: If the provided context does NOT contain the exact answer to the user's specific question (for example, they ask how to delete a ticket, but the context only explains how to open or view tickets), you MUST reply EXACTLY with the word: NOT_FOUND. Do not try to guess or invent an answer based on unrelated context. "
                        "If the context DOES answer the question accurately, be conversational, encouraging, and use simple language. "
                        "Never mention 'the FAQ', 'the context', or 'the database'. Just answer naturally. "
                        "Always start your response with a ✅ emoji and end with: '*Let me know if you need any more help! 😊*'"
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"My name is {user_name}. My question is: \"{question}\"\n\n"
                        f"FAQ Context:\n{context_str}"
                    ),
                },
            ],
            model="llama-3.1-8b-instant",
            max_tokens=400,
            temperature=0.1,
        )
        
        if not summary or "NOT_FOUND" in str(summary).strip():
            return _get_faq_fallback()
            
        answer = fb + str(summary)
    except Exception as e:
        log.error("FAQ LLM synthesis failed: %s", e)
        return _get_faq_fallback()

    return {
        "answer": answer,
        "action_buttons": [],
    }


def handle_knowledge(question: str, ctx: ToolContext) -> dict:
    """Semantic search on knowledge base, then summarize with fast model."""
    from app.ai.services.llm_service import call_groq

    results = search_knowledge(question, match_count=4)
    if not results:
        return {
            "answer": "📚 I couldn't find anything relevant in the knowledge base for that question. Try rephrasing or ask about a specific asset/ticket.",
            "action_buttons": [],
        }

    context_parts = [f"- {r.get('title', 'Article')}: {r.get('content', '')[:300]}" for r in results]
    context_str = "\n".join(context_parts)

    fallback_msg = ""
    try:
        summary, fallback_msg = call_groq(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are PredictiX Assistant. Summarize the following knowledge base articles to answer the user's question. "
                        "Be concise (3-5 sentences). Use professional language. End with 'Is there anything else I can help with?'"
                    ),
                },
                {"role": "user", "content": f"Question: {question}\n\nKnowledge Base:\n{context_str}"},
            ],
            model="llama-3.1-8b-instant",
            max_tokens=300,
            temperature=0.4,
        )
    except Exception as e:
        log.error("Knowledge summarization failed: %s", e)
        summary = context_str

    return {
        "answer": fallback_msg + f"📚 {summary}",
        "action_buttons": [],
    }


def handle_database(question: str, ctx: ToolContext) -> dict:
    """Two-agent pipeline: Table Selector → SQL Generator → Execute → Summarize."""
    from app.ai.services.llm_service import call_groq

    def _get_generic_fallback() -> dict:
        return {
            "answer": "Please reach out to our admins at **neuromindspredictix@gmail.com** and they'll get back to you as soon as possible.",
            "action_buttons": [{"label": "Copy Admin Email", "path": "copy:neuromindspredictix@gmail.com"}],
        }

    # Collect fallback messages from models
    fallback_msg = ""

    # ── Step 0: Dashboard Fast-Path (100% UI Parity) ─────────────────────────
    q_lower = question.lower()
    is_summary = any(w in q_lower for w in ["summary", "overview", "dashboard stats", "all stats"])
    if is_summary:
        try:
            from app.routers.admin_dashboard import _build_admin_summary
            from app.models import Profile

            # Get exact dashboard KPIs
            summary_data = _build_admin_summary(ctx.db, ctx.warehouse_id)
            kpis = summary_data.get("kpis", {})

            # Get exact user counts matching the Users page logic
            users_q = ctx.db.query(Profile)
            if ctx.warehouse_id:
                users_q = users_q.filter((Profile.warehouse_id == ctx.warehouse_id) | (Profile.warehouse_id.is_(None)))
            all_users = users_q.all()

            total_users = len(all_users)
            active_users = sum(1 for u in all_users if getattr(u, "status", "").lower() == "active")
            admins = sum(1 for u in all_users if getattr(u, "role", "").lower() == "admin")
            super_admins = sum(1 for u in all_users if getattr(u, "role", "").lower() == "super_admin")
            regular_users = sum(1 for u in all_users if getattr(u, "role", "").lower() == "user")

            # Fake the SQL rows output so the Summarizer handles it perfectly
            rows = [
                {"Metric": "Total Users", "Count": total_users},
                {"Metric": "Active Users", "Count": active_users},
                {"Metric": "Admins", "Count": admins},
                {"Metric": "Super Admins", "Count": super_admins},
                {"Metric": "Regular Users", "Count": regular_users},
                {"Metric": "Total Assets", "Count": kpis.get("totalAssets", 0)},
                {"Metric": "Critical Alerts", "Count": kpis.get("criticalAlerts", 0)},
                {"Metric": "Open Tickets", "Count": kpis.get("openTickets", 0)},
                {"Metric": "High Priority Tickets", "Count": kpis.get("highPriorityTickets", 0)},
                {"Metric": "Predicted Failures", "Count": kpis.get("predictedFailures", 0)},
            ]
            
            # Jump straight to Step 4: Summarize
            selected_tables = ["users", "tickets", "assets", "dashboard"]
            sql = "DASHBOARD_FAST_PATH"
            goto_summarizer = True
        except Exception as e:
            log.error("Dashboard fast-path failed: %s", e)
            goto_summarizer = False
    else:
        goto_summarizer = False

    if not goto_summarizer:
        # ── Step 1: Table Selector (fast model) ──────────────────────────────────
        table_list = ", ".join(DB_SCHEMAS.keys())
        selector_prompt = (
            f"You are a database table selector for PredictiX (Smart Asset Management System).\n"
            f"The user asked: \"{question}\"\n\n"
            f"Available tables: {table_list}\n\n"
            "Respond with ONLY a comma-separated list of up to 4 table names that are needed to answer this question. "
            "No explanations, no other text."
        )
        try:
            raw_tables, fb = call_groq(
                messages=[{"role": "user", "content": selector_prompt}],
                model="llama-3.1-8b-instant",
                max_tokens=60,
                temperature=0.1,
            )
            if fb and not fallback_msg: fallback_msg = fb
            selected_tables = [t.strip() for t in str(raw_tables).split(",") if t.strip() in DB_SCHEMAS]
        except Exception as e:
            log.error("Table selector failed: %s", e)
            selected_tables = ["tickets", "assets"]

        if not selected_tables:
            selected_tables = ["tickets", "assets"]

        # ── Step 2: SQL Generator (heavy model) ──────────────────────────────────
        schema_str = "\n".join(
            f"Table '{t}': columns → {DB_SCHEMAS[t]}" for t in selected_tables
        )

        # Build role-based scoping instruction
        if ctx.is_admin:
            scope_instruction = "The current user is an ADMIN. You may query ALL records across the entire system."
            if ctx.warehouse_id:
                scope_instruction += f" The admin is scoped to warehouse_id = '{ctx.warehouse_id}'."
        else:
            scope_instruction = (
                f"The current user is a STANDARD USER (id='{ctx.user_id}'). "
                "You MUST add a WHERE clause to only show records where created_by = '{user_id}' OR assigned_to = '{user_id}'. "
                "Never expose other users' private data."
            ).replace("{user_id}", ctx.user_id)

        sql_prompt = (
            f"You are an expert PostgreSQL developer for PredictiX.\n\n"
            f"SCHEMA:\n{schema_str}\n\n"
            f"SCOPING RULE: {scope_instruction}\n\n"
            f"TASK: Write a raw PostgreSQL SELECT query to answer: \"{question}\"\n\n"
            "RULES:\n"
            "- Output ONLY the raw SQL, no markdown, no backticks, no explanation.\n"
            "- Only SELECT queries allowed. No INSERT/UPDATE/DELETE/DROP.\n"
            "- LIMIT results to 50 rows maximum.\n"
            "- If the question asks 'how many per category', 'count by', 'in each', 'by role', 'by status', 'by type', "
            "  you MUST use GROUP BY and COUNT(*) to return every category with its count. "
            "  Also add ORDER BY count DESC so highest counts appear first.\n"
            "- If the question asks for a total count, use COUNT(*).\n"
            "- If impossible, output: ERROR: <reason>"
        )
        try:
            raw_sql, fb = call_groq(
                messages=[{"role": "user", "content": sql_prompt}],
                model="llama-3.3-70b-versatile",
                max_tokens=350,
                temperature=0.1,
            )
            if fb and not fallback_msg: fallback_msg = fb
            sql = str(raw_sql).strip().lstrip("```sql").lstrip("```").rstrip("```").strip()
        except Exception as e:
            log.error("SQL generator failed: %s", e)
            return {"answer": "⚠️ I had trouble generating a database query. Please try again shortly.", "action_buttons": []}

        if sql.startswith("ERROR:"):
            return _get_generic_fallback()

        # Security guard: block any mutation
        import re
        sql_upper = sql.upper()
        for dangerous in ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "TRUNCATE", "GRANT"]:
            if re.search(rf"\b{dangerous}\b", sql_upper):
                return _get_generic_fallback()

        # ── Step 3: Execute ───────────────────────────────────────────────────────
        if ctx.db is None:
            return {"answer": "⚠️ Database is not available right now. Please try again in a moment.", "action_buttons": []}

        try:
            result = ctx.db.execute(text(sql)).fetchall()
            if not result:
                return {"answer": "📊 The query ran successfully but returned no results. The data matching your request may not exist yet.", "action_buttons": []}
            keys = list(result[0]._mapping.keys())
            rows = [dict(zip(keys, row)) for row in result[:50]]
        except Exception as e:
            log.error("SQL execution failed: %s | SQL: %s", e, sql)
            return {
                "answer": "⚠️ The query could not be executed. The database may be temporarily unavailable — please try again in a moment.",
                "action_buttons": [],
            }

    # ── Step 4: Summarize (fast model) ───────────────────────────────────────
    row_str = str(rows[:30])  # cap context to keep tokens low

    # Build a direct plain-text fallback from the raw rows (used if LLM fails)
    def _build_fallback(rows: list[dict]) -> str:
        if not rows:
            return "📊 No data found."
        lines = [f"📊 **Results ({len(rows)} record{'s' if len(rows) != 1 else ''}):**\n"]
        for row in rows:
            keys = list(row.keys())
            # Clean format for two-column stats (e.g. Metric/Count, Category/Total)
            if len(keys) == 2 and str(keys[1]).lower() in ["count", "value", "total", "amount", "sum"]:
                lines.append(f"• **{row[keys[0]]}:** {row[keys[1]]}")
            else:
                line_parts = []
                for k, v in row.items():
                    if v is not None and str(v).strip():
                        pretty_key = str(k).replace("_", " ").title()
                        line_parts.append(f"**{pretty_key}:** {v}")
                lines.append("• " + " | ".join(line_parts))
        return "\n".join(lines)

    summarizer_prompt = (
        f"You are PredictiX Assistant. A user asked: \"{question}\"\n"
        f"The database returned this data: {row_str}\n\n"
        "INSTRUCTIONS — follow these EXACTLY:\n"
        "1. Start with a ONE-LINE summary stating the TOTAL count.\n"
        "2. Then list EVERY SINGLE category/group/status/role from the data with its exact count.\n"
        "   Format each line as: [emoji] **Category Name:** X items\n"
        "3. Use 👥 for user roles, 🎫 for ticket status, ⚙️ for asset types, 📊 for general stats.\n"
        "4. Quote EXACT numbers — never round or approximate.\n"
        "5. Never say 'Found N records matching' — always show the actual breakdown.\n"
        "6. Never expose raw UUIDs.\n"
        "7. End with a polite, helpful closing sentence."
    )
    try:
        summary, fb = call_groq(
            messages=[{"role": "user", "content": summarizer_prompt}],
            model="llama-3.1-8b-instant",
            max_tokens=400,
            temperature=0.2,
        )
        if fb and not fallback_msg: fallback_msg = fb
        if not summary or len(str(summary).strip()) < 10:
            summary = _build_fallback(rows)
    except Exception as e:
        log.error("Summarizer failed: %s", e)
        summary = _build_fallback(rows)

    # Determine interactive action buttons based on queried tables
    action_buttons = []
    if "profiles" in selected_tables or "users" in selected_tables:
        action_buttons.append({"label": "Manage Users", "path": "/admin/users"})
    if "tickets" in selected_tables:
        action_buttons.append({"label": "View Tickets", "path": "/admin/tickets"})
    if "assets" in selected_tables:
        action_buttons.append({"label": "View Assets", "path": "/admin/assets"})
    if "warehouses" in selected_tables:
        action_buttons.append({"label": "View Warehouses", "path": "/admin/warehouse"})

    # Limit to 2 buttons max so it doesn't clutter the UI
    action_buttons = action_buttons[:2]

    return {
        "answer": fallback_msg + str(summary),
        "action_buttons": action_buttons,
    }



def handle_prediction_info(question: str, ctx: ToolContext) -> dict:
    """Handles questions about how to USE prediction models + shows predictions data."""
    q_lower = question.lower()

    # If the user wants to KNOW HOW to use the models → give guidance + button
    how_to_keywords = ["how", "how to", "use", "run", "generate", "where", "start", "launch"]
    is_how_to = any(kw in q_lower for kw in how_to_keywords)

    if is_how_to and "predict" in q_lower or "report" in q_lower or "cost estimat" in q_lower:
        answer = (
            "🤖 **AI Prediction Models in PredictiX:**\n\n"
            "**🔮 Failure Prediction (Predictive Maintenance)**\n"
            "• Go to any Asset → Click **Run Prediction** → The AI calculates failure probability, health score, and predicted maintenance date.\n\n"
            "**💰 Cost Estimation**\n"
            "• Go to **Reports** → Select **Cost Prediction** → Choose an asset or warehouse to estimate maintenance costs.\n\n"
            "**🎫 Ticket AI Classification**\n"
            "• When creating or viewing a ticket, the AI automatically predicts its category and priority.\n\n"
            "**📦 Batch Predictions (PDM)**\n"
            "• Go to **Reports** → Select **Batch PDM** to run predictions for all assets at once.\n\n"
            "Please visit the Helpdesk section for more details. Contact admin at neuromindspredictix@gmail.com."
        )
        buttons = [
            {"label": "Go to Reports / Predictions", "path": "/admin/reports"},
            {"label": "Go to Assets", "path": "/admin/assets"},
        ]
        return {"answer": answer, "action_buttons": buttons}

    # Otherwise, query the actual prediction data from DB
    return handle_database(question, ctx)
